CREATE TABLE brand(
   id INTEGER  NOT NULL PRIMARY KEY ,
  name VARCHAR(21) NOT NULL
);
INSERT INTO brand(id,name) VALUES (1,'CHEVROLET');
INSERT INTO brand(id,name) VALUES (2,'VOLKSWAGEN');
INSERT INTO brand(id,name) VALUES (2,'VOLKSWAGEN');
INSERT INTO brand(id,name) VALUES (3,'FIAT');
INSERT INTO brand(id,name) VALUES (4,'MERCEDES-BENZ');
INSERT INTO brand(id,name) VALUES (5,'CITROEN');
INSERT INTO brand(id,name) VALUES (6,'CHANA');
INSERT INTO brand(id,name) VALUES (7,'HONDA');
INSERT INTO brand(id,name) VALUES (8,'SUBARU');
INSERT INTO brand(id,name) VALUES (10,'FERRARI');
INSERT INTO brand(id,name) VALUES (11,'BUGATTI');
INSERT INTO brand(id,name) VALUES (12,'LAMBORGHINI');
INSERT INTO brand(id,name) VALUES (13,'FORD');
INSERT INTO brand(id,name) VALUES (14,'HYUNDAI');
INSERT INTO brand(id,name) VALUES (15,'JAC');
INSERT INTO brand(id,name) VALUES (16,'KIA');
INSERT INTO brand(id,name) VALUES (17,'GURGEL');
INSERT INTO brand(id,name) VALUES (18,'DODGE');
INSERT INTO brand(id,name) VALUES (19,'CHRYSLER');
INSERT INTO brand(id,name) VALUES (20,'BENTLEY');
INSERT INTO brand(id,name) VALUES (21,'SSANGYONG');
INSERT INTO brand(id,name) VALUES (22,'PEUGEOT');
INSERT INTO brand(id,name) VALUES (23,'TOYOTA');
INSERT INTO brand(id,name) VALUES (24,'RENAULT');
INSERT INTO brand(id,name) VALUES (25,'ACURA');
INSERT INTO brand(id,name) VALUES (26,'ADAMO');
INSERT INTO brand(id,name) VALUES (27,'AGRALE');
INSERT INTO brand(id,name) VALUES (28,'ALFA ROMEO');
INSERT INTO brand(id,name) VALUES (29,'AMERICAR');
INSERT INTO brand(id,name) VALUES (31,'ASTON MARTIN');
INSERT INTO brand(id,name) VALUES (32,'AUDI');
INSERT INTO brand(id,name) VALUES (34,'BEACH');
INSERT INTO brand(id,name) VALUES (35,'BIANCO');
INSERT INTO brand(id,name) VALUES (36,'BMW');
INSERT INTO brand(id,name) VALUES (37,'BORGWARD');
INSERT INTO brand(id,name) VALUES (38,'BRILLIANCE');
INSERT INTO brand(id,name) VALUES (41,'BUICK');
INSERT INTO brand(id,name) VALUES (42,'CBT');
INSERT INTO brand(id,name) VALUES (43,'NISSAN');
INSERT INTO brand(id,name) VALUES (44,'CHAMONIX');
INSERT INTO brand(id,name) VALUES (46,'CHEDA');
INSERT INTO brand(id,name) VALUES (47,'CHERY');
INSERT INTO brand(id,name) VALUES (48,'CORD');
INSERT INTO brand(id,name) VALUES (49,'COYOTE');
INSERT INTO brand(id,name) VALUES (50,'CROSS LANDER');
INSERT INTO brand(id,name) VALUES (51,'DAEWOO');
INSERT INTO brand(id,name) VALUES (52,'DAIHATSU');
INSERT INTO brand(id,name) VALUES (53,'VOLVO');
INSERT INTO brand(id,name) VALUES (54,'DE SOTO');
INSERT INTO brand(id,name) VALUES (55,'DETOMAZO');
INSERT INTO brand(id,name) VALUES (56,'DELOREAN');
INSERT INTO brand(id,name) VALUES (57,'DKW-VEMAG');
INSERT INTO brand(id,name) VALUES (59,'SUZUKI');
INSERT INTO brand(id,name) VALUES (60,'EAGLE');
INSERT INTO brand(id,name) VALUES (61,'EFFA');
INSERT INTO brand(id,name) VALUES (63,'ENGESA');
INSERT INTO brand(id,name) VALUES (64,'ENVEMO');
INSERT INTO brand(id,name) VALUES (65,'FARUS');
INSERT INTO brand(id,name) VALUES (66,'FERCAR');
INSERT INTO brand(id,name) VALUES (68,'FNM');
INSERT INTO brand(id,name) VALUES (69,'PONTIAC');
INSERT INTO brand(id,name) VALUES (70,'PORSCHE');
INSERT INTO brand(id,name) VALUES (72,'GEO');
INSERT INTO brand(id,name) VALUES (74,'GRANCAR');
INSERT INTO brand(id,name) VALUES (75,'GREAT WALL');
INSERT INTO brand(id,name) VALUES (76,'HAFEI');
INSERT INTO brand(id,name) VALUES (78,'HOFSTETTER');
INSERT INTO brand(id,name) VALUES (79,'HUDSON');
INSERT INTO brand(id,name) VALUES (80,'HUMMER');
INSERT INTO brand(id,name) VALUES (82,'INFINITI');
INSERT INTO brand(id,name) VALUES (83,'INTERNATIONAL');
INSERT INTO brand(id,name) VALUES (86,'JAGUAR');
INSERT INTO brand(id,name) VALUES (87,'JEEP');
INSERT INTO brand(id,name) VALUES (88,'JINBEI');
INSERT INTO brand(id,name) VALUES (89,'JPX');
INSERT INTO brand(id,name) VALUES (90,'KAISER');
INSERT INTO brand(id,name) VALUES (91,'KOENIGSEGG');
INSERT INTO brand(id,name) VALUES (92,'LAUTOMOBILE');
INSERT INTO brand(id,name) VALUES (93,'LAUTOCRAFT');
INSERT INTO brand(id,name) VALUES (94,'LADA');
INSERT INTO brand(id,name) VALUES (95,'LANCIA');
INSERT INTO brand(id,name) VALUES (96,'LAND ROVER');
INSERT INTO brand(id,name) VALUES (97,'LEXUS');
INSERT INTO brand(id,name) VALUES (98,'LIFAN');
INSERT INTO brand(id,name) VALUES (99,'LINCOLN');
INSERT INTO brand(id,name) VALUES (100,'LOBINI');
INSERT INTO brand(id,name) VALUES (101,'LOTUS');
INSERT INTO brand(id,name) VALUES (102,'MAHINDRA');
INSERT INTO brand(id,name) VALUES (104,'MASERATI');
INSERT INTO brand(id,name) VALUES (106,'MATRA');
INSERT INTO brand(id,name) VALUES (107,'MAYBACH');
INSERT INTO brand(id,name) VALUES (108,'MAZDA');
INSERT INTO brand(id,name) VALUES (109,'MENON');
INSERT INTO brand(id,name) VALUES (110,'MERCURY');
INSERT INTO brand(id,name) VALUES (111,'MITSUBISHI');
INSERT INTO brand(id,name) VALUES (112,'MG');
INSERT INTO brand(id,name) VALUES (113,'MINI');
INSERT INTO brand(id,name) VALUES (114,'MIURA');
INSERT INTO brand(id,name) VALUES (115,'MORRIS');
INSERT INTO brand(id,name) VALUES (116,'MP LAFER');
INSERT INTO brand(id,name) VALUES (117,'MPLM');
INSERT INTO brand(id,name) VALUES (118,'NEWTRACK');
INSERT INTO brand(id,name) VALUES (119,'NISSIN');
INSERT INTO brand(id,name) VALUES (120,'OLDSMOBILE');
INSERT INTO brand(id,name) VALUES (121,'PAG');
INSERT INTO brand(id,name) VALUES (122,'PAGANI');
INSERT INTO brand(id,name) VALUES (123,'PLYMOUTH');
INSERT INTO brand(id,name) VALUES (124,'PUMA');
INSERT INTO brand(id,name) VALUES (125,'RENO');
INSERT INTO brand(id,name) VALUES (126,'REVA-I');
INSERT INTO brand(id,name) VALUES (127,'ROLLS-ROYCE');
INSERT INTO brand(id,name) VALUES (129,'ROMI');
INSERT INTO brand(id,name) VALUES (130,'SEAT');
INSERT INTO brand(id,name) VALUES (131,'UTILITARIOS AGRICOLAS');
INSERT INTO brand(id,name) VALUES (132,'SHINERAY');
INSERT INTO brand(id,name) VALUES (137,'SAAB');
INSERT INTO brand(id,name) VALUES (139,'SHORT');
INSERT INTO brand(id,name) VALUES (141,'SIMCA');
INSERT INTO brand(id,name) VALUES (142,'SMART');
INSERT INTO brand(id,name) VALUES (143,'SPYKER');
INSERT INTO brand(id,name) VALUES (144,'STANDARD');
INSERT INTO brand(id,name) VALUES (145,'STUDEBAKER');
INSERT INTO brand(id,name) VALUES (146,'TAC');
INSERT INTO brand(id,name) VALUES (147,'TANGER');
INSERT INTO brand(id,name) VALUES (148,'TRIUMPH');
INSERT INTO brand(id,name) VALUES (149,'TROLLER');
INSERT INTO brand(id,name) VALUES (150,'UNIMOG');
INSERT INTO brand(id,name) VALUES (154,'WIESMANN');
INSERT INTO brand(id,name) VALUES (155,'CADILLAC');
INSERT INTO brand(id,name) VALUES (156,'AM GEN');
INSERT INTO brand(id,name) VALUES (157,'BUGGY');
INSERT INTO brand(id,name) VALUES (158,'WILLYS OVERLAND');
INSERT INTO brand(id,name) VALUES (161,'KASEA');
INSERT INTO brand(id,name) VALUES (162,'SATURN');
INSERT INTO brand(id,name) VALUES (163,'SWELL MINI');
INSERT INTO brand(id,name) VALUES (175,'SKODA');
INSERT INTO brand(id,name) VALUES (239,'KARMANN GHIA');
INSERT INTO brand(id,name) VALUES (254,'KART');
INSERT INTO brand(id,name) VALUES (258,'HANOMAG');
INSERT INTO brand(id,name) VALUES (261,'OUTROS');
INSERT INTO brand(id,name) VALUES (265,'HILLMAN');
INSERT INTO brand(id,name) VALUES (288,'HRG');
INSERT INTO brand(id,name) VALUES (295,'GAIOLA');
INSERT INTO brand(id,name) VALUES (338,'TATA');
INSERT INTO brand(id,name) VALUES (341,'DITALLY');
INSERT INTO brand(id,name) VALUES (345,'RELY');
INSERT INTO brand(id,name) VALUES (346,'MCLAREN');
INSERT INTO brand(id,name) VALUES (534,'GEELY');
