CREATE TABLE model(
   id      INTEGER  NOT NULL PRIMARY KEY 
  ,brand_id INTEGER  NOT NULL
  ,name    VARCHAR(21) NOT NULL
);

INSERT INTO model(id,brand_id,name) VALUES (1,25,'INTEGRA');
INSERT INTO model(id,brand_id,name) VALUES (2,25,'LEGEND');
INSERT INTO model(id,brand_id,name) VALUES (3,25,'NSX');
INSERT INTO model(id,brand_id,name) VALUES (4,27,'MARRUA');
INSERT INTO model(id,brand_id,name) VALUES (5,28,'145');
INSERT INTO model(id,brand_id,name) VALUES (6,28,'147');
INSERT INTO model(id,brand_id,name) VALUES (7,28,'155');
INSERT INTO model(id,brand_id,name) VALUES (8,28,'156');
INSERT INTO model(id,brand_id,name) VALUES (9,28,'164');
INSERT INTO model(id,brand_id,name) VALUES (10,28,'166');
INSERT INTO model(id,brand_id,name) VALUES (11,28,'2300');
INSERT INTO model(id,brand_id,name) VALUES (12,28,'SPidER');
INSERT INTO model(id,brand_id,name) VALUES (13,156,'HUMMER');
INSERT INTO model(id,brand_id,name) VALUES (14,16,'AM-825');
INSERT INTO model(id,brand_id,name) VALUES (15,16,'HI-TOPIC');
INSERT INTO model(id,brand_id,name) VALUES (16,16,'ROCSTA');
INSERT INTO model(id,brand_id,name) VALUES (17,16,'TOPIC');
INSERT INTO model(id,brand_id,name) VALUES (18,16,'TOWNER');
INSERT INTO model(id,brand_id,name) VALUES (19,32,'100');
INSERT INTO model(id,brand_id,name) VALUES (20,32,'80');
INSERT INTO model(id,brand_id,name) VALUES (21,32,'A1');
INSERT INTO model(id,brand_id,name) VALUES (22,32,'A3');
INSERT INTO model(id,brand_id,name) VALUES (23,32,'A4 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (24,32,'A5 COUPE');
INSERT INTO model(id,brand_id,name) VALUES (25,32,'A6 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (26,32,'A7');
INSERT INTO model(id,brand_id,name) VALUES (27,32,'A8');
INSERT INTO model(id,brand_id,name) VALUES (30,32,'Q3');
INSERT INTO model(id,brand_id,name) VALUES (31,32,'Q5');
INSERT INTO model(id,brand_id,name) VALUES (32,32,'Q7');
INSERT INTO model(id,brand_id,name) VALUES (33,32,'R8');
INSERT INTO model(id,brand_id,name) VALUES (34,32,'RS3');
INSERT INTO model(id,brand_id,name) VALUES (35,32,'RS4');
INSERT INTO model(id,brand_id,name) VALUES (36,32,'RS5');
INSERT INTO model(id,brand_id,name) VALUES (37,32,'RS6');
INSERT INTO model(id,brand_id,name) VALUES (38,32,'S3');
INSERT INTO model(id,brand_id,name) VALUES (39,32,'S4 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (40,32,'S6 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (41,32,'S8');
INSERT INTO model(id,brand_id,name) VALUES (42,32,'TT');
INSERT INTO model(id,brand_id,name) VALUES (43,32,'TTS');
INSERT INTO model(id,brand_id,name) VALUES (86,157,'BUGGY');
INSERT INTO model(id,brand_id,name) VALUES (87,155,'DEVILLE');
INSERT INTO model(id,brand_id,name) VALUES (88,155,'ELDORADO');
INSERT INTO model(id,brand_id,name) VALUES (89,155,'SEVILLE');
INSERT INTO model(id,brand_id,name) VALUES (90,42,'JAVALI');
INSERT INTO model(id,brand_id,name) VALUES (92,6,'MINI STAR FAMILY');
INSERT INTO model(id,brand_id,name) VALUES (93,6,'MINI STAR UTILITY');
INSERT INTO model(id,brand_id,name) VALUES (95,47,'CIELO');
INSERT INTO model(id,brand_id,name) VALUES (96,47,'FACE');
INSERT INTO model(id,brand_id,name) VALUES (97,47,'QQ');
INSERT INTO model(id,brand_id,name) VALUES (98,47,'S-18');
INSERT INTO model(id,brand_id,name) VALUES (99,47,'TIGGO');
INSERT INTO model(id,brand_id,name) VALUES (100,19,'300C');
INSERT INTO model(id,brand_id,name) VALUES (101,19,'CARAVAN');
INSERT INTO model(id,brand_id,name) VALUES (102,19,'CIRRUS');
INSERT INTO model(id,brand_id,name) VALUES (103,19,'GRAN CARAVAN');
INSERT INTO model(id,brand_id,name) VALUES (104,19,'LE BARON');
INSERT INTO model(id,brand_id,name) VALUES (105,19,'NEON');
INSERT INTO model(id,brand_id,name) VALUES (106,19,'PT CRUISER');
INSERT INTO model(id,brand_id,name) VALUES (107,19,'SEBRING');
INSERT INTO model(id,brand_id,name) VALUES (108,19,'STRATUS');
INSERT INTO model(id,brand_id,name) VALUES (109,19,'TOWN E COUNTRY');
INSERT INTO model(id,brand_id,name) VALUES (110,19,'VISION');
INSERT INTO model(id,brand_id,name) VALUES (111,5,'AIRCROSS');
INSERT INTO model(id,brand_id,name) VALUES (112,5,'AX');
INSERT INTO model(id,brand_id,name) VALUES (113,5,'BERLINGO');
INSERT INTO model(id,brand_id,name) VALUES (114,5,'BX');
INSERT INTO model(id,brand_id,name) VALUES (115,5,'C3');
INSERT INTO model(id,brand_id,name) VALUES (116,5,'C4');
INSERT INTO model(id,brand_id,name) VALUES (117,5,'C5');
INSERT INTO model(id,brand_id,name) VALUES (118,5,'C6');
INSERT INTO model(id,brand_id,name) VALUES (119,5,'C8');
INSERT INTO model(id,brand_id,name) VALUES (120,5,'DS3');
INSERT INTO model(id,brand_id,name) VALUES (121,5,'EVASION');
INSERT INTO model(id,brand_id,name) VALUES (122,5,'JUMPER');
INSERT INTO model(id,brand_id,name) VALUES (123,5,'XANTIA');
INSERT INTO model(id,brand_id,name) VALUES (124,5,'XM');
INSERT INTO model(id,brand_id,name) VALUES (125,5,'XSARA');
INSERT INTO model(id,brand_id,name) VALUES (126,5,'ZX');
INSERT INTO model(id,brand_id,name) VALUES (127,50,'CL-244');
INSERT INTO model(id,brand_id,name) VALUES (128,50,'CL-330');
INSERT INTO model(id,brand_id,name) VALUES (129,51,'ESPERO');
INSERT INTO model(id,brand_id,name) VALUES (130,51,'LANOS');
INSERT INTO model(id,brand_id,name) VALUES (131,51,'LEGANZA');
INSERT INTO model(id,brand_id,name) VALUES (132,51,'NUBIRA');
INSERT INTO model(id,brand_id,name) VALUES (133,51,'PRINCE');
INSERT INTO model(id,brand_id,name) VALUES (134,51,'RACER');
INSERT INTO model(id,brand_id,name) VALUES (135,51,'SUPER SALON');
INSERT INTO model(id,brand_id,name) VALUES (136,51,'TICO');
INSERT INTO model(id,brand_id,name) VALUES (137,52,'APPLAUSE');
INSERT INTO model(id,brand_id,name) VALUES (138,52,'CHARADE');
INSERT INTO model(id,brand_id,name) VALUES (139,52,'CUORE');
INSERT INTO model(id,brand_id,name) VALUES (140,52,'FEROZA');
INSERT INTO model(id,brand_id,name) VALUES (141,52,'GRAN MOVE');
INSERT INTO model(id,brand_id,name) VALUES (142,52,'MOVE VAN');
INSERT INTO model(id,brand_id,name) VALUES (143,52,'TERIOS');
INSERT INTO model(id,brand_id,name) VALUES (144,18,'AVENGER');
INSERT INTO model(id,brand_id,name) VALUES (145,18,'DAKOTA');
INSERT INTO model(id,brand_id,name) VALUES (146,18,'JOURNEY');
INSERT INTO model(id,brand_id,name) VALUES (147,18,'RAM');
INSERT INTO model(id,brand_id,name) VALUES (148,18,'STEALTH');
INSERT INTO model(id,brand_id,name) VALUES (151,61,'M-100');
INSERT INTO model(id,brand_id,name) VALUES (152,61,'PLUTUS');
INSERT INTO model(id,brand_id,name) VALUES (153,61,'START');
INSERT INTO model(id,brand_id,name) VALUES (155,61,'ULC');
INSERT INTO model(id,brand_id,name) VALUES (158,63,'ENGESA');
INSERT INTO model(id,brand_id,name) VALUES (159,64,'CAMPER');
INSERT INTO model(id,brand_id,name) VALUES (160,64,'MASTER');
INSERT INTO model(id,brand_id,name) VALUES (161,10,'348');
INSERT INTO model(id,brand_id,name) VALUES (162,10,'355');
INSERT INTO model(id,brand_id,name) VALUES (163,10,'360');
INSERT INTO model(id,brand_id,name) VALUES (164,10,'456');
INSERT INTO model(id,brand_id,name) VALUES (165,10,'550');
INSERT INTO model(id,brand_id,name) VALUES (166,10,'575M');
INSERT INTO model(id,brand_id,name) VALUES (167,10,'612');
INSERT INTO model(id,brand_id,name) VALUES (168,10,'CALIFORNIA');
INSERT INTO model(id,brand_id,name) VALUES (169,10,'F430');
INSERT INTO model(id,brand_id,name) VALUES (170,10,'F599');
INSERT INTO model(id,brand_id,name) VALUES (171,3,'147');
INSERT INTO model(id,brand_id,name) VALUES (174,3,'500');
INSERT INTO model(id,brand_id,name) VALUES (175,3,'BRAVA');
INSERT INTO model(id,brand_id,name) VALUES (176,3,'BRAVO');
INSERT INTO model(id,brand_id,name) VALUES (178,3,'COUPE');
INSERT INTO model(id,brand_id,name) VALUES (179,3,'DOBLO');
INSERT INTO model(id,brand_id,name) VALUES (180,3,'DUCATO CARGO');
INSERT INTO model(id,brand_id,name) VALUES (181,3,'DUNA');
INSERT INTO model(id,brand_id,name) VALUES (182,3,'ELBA');
INSERT INTO model(id,brand_id,name) VALUES (183,3,'FIORINO');
INSERT INTO model(id,brand_id,name) VALUES (184,3,'FREEMONT');
INSERT INTO model(id,brand_id,name) VALUES (185,3,'GRAND SIENA');
INSERT INTO model(id,brand_id,name) VALUES (186,3,'idEA');
INSERT INTO model(id,brand_id,name) VALUES (187,3,'LINEA');
INSERT INTO model(id,brand_id,name) VALUES (188,3,'MAREA');
INSERT INTO model(id,brand_id,name) VALUES (189,3,'OGGI');
INSERT INTO model(id,brand_id,name) VALUES (190,3,'PALIO');
INSERT INTO model(id,brand_id,name) VALUES (191,3,'PANORAMA');
INSERT INTO model(id,brand_id,name) VALUES (192,3,'PREMIO');
INSERT INTO model(id,brand_id,name) VALUES (193,3,'PUNTO');
INSERT INTO model(id,brand_id,name) VALUES (194,3,'SIENA');
INSERT INTO model(id,brand_id,name) VALUES (195,3,'STILO');
INSERT INTO model(id,brand_id,name) VALUES (196,3,'STRADA');
INSERT INTO model(id,brand_id,name) VALUES (197,3,'TEMPRA');
INSERT INTO model(id,brand_id,name) VALUES (198,3,'TIPO');
INSERT INTO model(id,brand_id,name) VALUES (199,3,'UNO');
INSERT INTO model(id,brand_id,name) VALUES (201,13,'AEROSTAR');
INSERT INTO model(id,brand_id,name) VALUES (202,13,'ASPIRE');
INSERT INTO model(id,brand_id,name) VALUES (203,13,'BELINA');
INSERT INTO model(id,brand_id,name) VALUES (204,13,'CLUB WAGON');
INSERT INTO model(id,brand_id,name) VALUES (205,13,'CONTOUR');
INSERT INTO model(id,brand_id,name) VALUES (206,13,'CORCEL II');
INSERT INTO model(id,brand_id,name) VALUES (207,13,'COURIER');
INSERT INTO model(id,brand_id,name) VALUES (208,13,'CROWN VICTORIA');
INSERT INTO model(id,brand_id,name) VALUES (209,13,'DEL REY');
INSERT INTO model(id,brand_id,name) VALUES (210,13,'ECOSPORT');
INSERT INTO model(id,brand_id,name) VALUES (211,13,'EDGE');
INSERT INTO model(id,brand_id,name) VALUES (212,13,'ESCORT');
INSERT INTO model(id,brand_id,name) VALUES (213,13,'EXPEDITION');
INSERT INTO model(id,brand_id,name) VALUES (214,13,'EXPLORER');
INSERT INTO model(id,brand_id,name) VALUES (215,13,'F-100');
INSERT INTO model(id,brand_id,name) VALUES (216,13,'F-1000');
INSERT INTO model(id,brand_id,name) VALUES (217,13,'F-150');
INSERT INTO model(id,brand_id,name) VALUES (218,13,'F-250');
INSERT INTO model(id,brand_id,name) VALUES (219,13,'FIESTA');
INSERT INTO model(id,brand_id,name) VALUES (220,13,'FOCUS');
INSERT INTO model(id,brand_id,name) VALUES (221,13,'FURGLAINE');
INSERT INTO model(id,brand_id,name) VALUES (222,13,'FUSION');
INSERT INTO model(id,brand_id,name) VALUES (223,13,'IBIZA');
INSERT INTO model(id,brand_id,name) VALUES (224,13,'KA');
INSERT INTO model(id,brand_id,name) VALUES (225,13,'MONDEO');
INSERT INTO model(id,brand_id,name) VALUES (226,13,'MUSTANG');
INSERT INTO model(id,brand_id,name) VALUES (227,13,'PAMPA');
INSERT INTO model(id,brand_id,name) VALUES (228,13,'PROBE');
INSERT INTO model(id,brand_id,name) VALUES (229,13,'RANGER');
INSERT INTO model(id,brand_id,name) VALUES (230,13,'VERSAILLES ROYALE');
INSERT INTO model(id,brand_id,name) VALUES (231,13,'TAURUS');
INSERT INTO model(id,brand_id,name) VALUES (232,13,'THUNDERBIRD');
INSERT INTO model(id,brand_id,name) VALUES (233,13,'TRANSIT');
INSERT INTO model(id,brand_id,name) VALUES (234,13,'VERONA');
INSERT INTO model(id,brand_id,name) VALUES (235,13,'VERSAILLES');
INSERT INTO model(id,brand_id,name) VALUES (236,13,'WINDSTAR');
INSERT INTO model(id,brand_id,name) VALUES (238,1,'A-10');
INSERT INTO model(id,brand_id,name) VALUES (239,1,'A-20');
INSERT INTO model(id,brand_id,name) VALUES (240,1,'AGILE');
INSERT INTO model(id,brand_id,name) VALUES (241,1,'ASTRA');
INSERT INTO model(id,brand_id,name) VALUES (242,1,'BLAZER');
INSERT INTO model(id,brand_id,name) VALUES (243,1,'BONANZA');
INSERT INTO model(id,brand_id,name) VALUES (245,1,'C-10');
INSERT INTO model(id,brand_id,name) VALUES (246,1,'C-20');
INSERT INTO model(id,brand_id,name) VALUES (247,1,'CALIBRA');
INSERT INTO model(id,brand_id,name) VALUES (248,1,'CAMARO');
INSERT INTO model(id,brand_id,name) VALUES (249,1,'CAPRICE');
INSERT INTO model(id,brand_id,name) VALUES (250,1,'CAPTIVA');
INSERT INTO model(id,brand_id,name) VALUES (251,1,'CARAVAN');
INSERT INTO model(id,brand_id,name) VALUES (252,1,'CAVALIER');
INSERT INTO model(id,brand_id,name) VALUES (253,1,'CELTA');
INSERT INTO model(id,brand_id,name) VALUES (255,1,'CHEVY');
INSERT INTO model(id,brand_id,name) VALUES (256,1,'CHEYNNE');
INSERT INTO model(id,brand_id,name) VALUES (258,1,'COBALT');
INSERT INTO model(id,brand_id,name) VALUES (259,1,'CORSA');
INSERT INTO model(id,brand_id,name) VALUES (262,1,'CORVETTE');
INSERT INTO model(id,brand_id,name) VALUES (263,1,'CRUZE');
INSERT INTO model(id,brand_id,name) VALUES (264,1,'D-10');
INSERT INTO model(id,brand_id,name) VALUES (265,1,'D-20');
INSERT INTO model(id,brand_id,name) VALUES (266,1,'IPANEMA');
INSERT INTO model(id,brand_id,name) VALUES (267,1,'KADETT');
INSERT INTO model(id,brand_id,name) VALUES (268,1,'LUMINA');
INSERT INTO model(id,brand_id,name) VALUES (269,1,'MALIBU');
INSERT INTO model(id,brand_id,name) VALUES (271,1,'MERIVA');
INSERT INTO model(id,brand_id,name) VALUES (272,1,'MONTANA');
INSERT INTO model(id,brand_id,name) VALUES (274,1,'OMEGA');
INSERT INTO model(id,brand_id,name) VALUES (275,1,'OPALA');
INSERT INTO model(id,brand_id,name) VALUES (276,1,'PRISMA');
INSERT INTO model(id,brand_id,name) VALUES (277,1,'S10');
INSERT INTO model(id,brand_id,name) VALUES (280,1,'SILVERADO');
INSERT INTO model(id,brand_id,name) VALUES (281,1,'SONIC');
INSERT INTO model(id,brand_id,name) VALUES (282,1,'SONOMA');
INSERT INTO model(id,brand_id,name) VALUES (283,1,'SPACEVAN');
INSERT INTO model(id,brand_id,name) VALUES (284,1,'SS10');
INSERT INTO model(id,brand_id,name) VALUES (285,1,'SUBURBAN');
INSERT INTO model(id,brand_id,name) VALUES (287,1,'SYCLONE');
INSERT INTO model(id,brand_id,name) VALUES (288,1,'TIGRA');
INSERT INTO model(id,brand_id,name) VALUES (289,1,'TRACKER');
INSERT INTO model(id,brand_id,name) VALUES (290,1,'TRAFIC');
INSERT INTO model(id,brand_id,name) VALUES (291,1,'VECTRA');
INSERT INTO model(id,brand_id,name) VALUES (292,1,'VERANEIO');
INSERT INTO model(id,brand_id,name) VALUES (293,1,'ZAFIRA');
INSERT INTO model(id,brand_id,name) VALUES (294,75,'HOVER');
INSERT INTO model(id,brand_id,name) VALUES (295,17,'BR-800');
INSERT INTO model(id,brand_id,name) VALUES (296,17,'CARAJAS');
INSERT INTO model(id,brand_id,name) VALUES (297,17,'TOCANTINS');
INSERT INTO model(id,brand_id,name) VALUES (298,17,'XAVANTE');
INSERT INTO model(id,brand_id,name) VALUES (299,17,'VIP');
INSERT INTO model(id,brand_id,name) VALUES (300,76,'TOWNER');
INSERT INTO model(id,brand_id,name) VALUES (301,7,'ACCORD');
INSERT INTO model(id,brand_id,name) VALUES (302,7,'CITY');
INSERT INTO model(id,brand_id,name) VALUES (303,7,'CIVIC');
INSERT INTO model(id,brand_id,name) VALUES (304,7,'CR-V');
INSERT INTO model(id,brand_id,name) VALUES (305,7,'FIT');
INSERT INTO model(id,brand_id,name) VALUES (306,7,'ODYSSEY');
INSERT INTO model(id,brand_id,name) VALUES (307,7,'PASSPORT');
INSERT INTO model(id,brand_id,name) VALUES (308,7,'PRELUDE');
INSERT INTO model(id,brand_id,name) VALUES (309,14,'ACCENT');
INSERT INTO model(id,brand_id,name) VALUES (310,14,'ATOS');
INSERT INTO model(id,brand_id,name) VALUES (311,14,'AZERA');
INSERT INTO model(id,brand_id,name) VALUES (312,14,'COUPE');
INSERT INTO model(id,brand_id,name) VALUES (314,14,'ELANTRA');
INSERT INTO model(id,brand_id,name) VALUES (315,14,'EXCEL');
INSERT INTO model(id,brand_id,name) VALUES (316,14,'GALLOPER');
INSERT INTO model(id,brand_id,name) VALUES (317,14,'GENESIS');
INSERT INTO model(id,brand_id,name) VALUES (318,14,'H1');
INSERT INTO model(id,brand_id,name) VALUES (319,14,'H100');
INSERT INTO model(id,brand_id,name) VALUES (321,14,'I30');
INSERT INTO model(id,brand_id,name) VALUES (323,14,'IX35');
INSERT INTO model(id,brand_id,name) VALUES (324,14,'MATRIX');
INSERT INTO model(id,brand_id,name) VALUES (325,14,'PORTER');
INSERT INTO model(id,brand_id,name) VALUES (326,14,'SANTA FE');
INSERT INTO model(id,brand_id,name) VALUES (327,14,'SCOUPE');
INSERT INTO model(id,brand_id,name) VALUES (328,14,'SONATA');
INSERT INTO model(id,brand_id,name) VALUES (329,14,'TERRACAN');
INSERT INTO model(id,brand_id,name) VALUES (330,14,'TRAJET');
INSERT INTO model(id,brand_id,name) VALUES (331,14,'TUCSON');
INSERT INTO model(id,brand_id,name) VALUES (332,14,'VELOSTER');
INSERT INTO model(id,brand_id,name) VALUES (333,14,'VERACRUZ');

INSERT INTO model(id,brand_id,name) VALUES (337,15,'J3');
INSERT INTO model(id,brand_id,name) VALUES (338,15,'J5');
INSERT INTO model(id,brand_id,name) VALUES (339,15,'J6');
INSERT INTO model(id,brand_id,name) VALUES (340,86,'DAIMLER');
INSERT INTO model(id,brand_id,name) VALUES (341,86,'S-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (342,86,'X-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (345,86,'MODELOS XJ');
INSERT INTO model(id,brand_id,name) VALUES (352,86,'MODELOS XK');
INSERT INTO model(id,brand_id,name) VALUES (354,87,'CHEROKEE');
INSERT INTO model(id,brand_id,name) VALUES (355,87,'COMMANDER');
INSERT INTO model(id,brand_id,name) VALUES (356,87,'COMPASS');
INSERT INTO model(id,brand_id,name) VALUES (357,87,'GRAND CHEROKEE');
INSERT INTO model(id,brand_id,name) VALUES (358,87,'WRANGLER');
INSERT INTO model(id,brand_id,name) VALUES (359,88,'TOPIC VAN');
INSERT INTO model(id,brand_id,name) VALUES (360,89,'JIPE MONTEZ');
INSERT INTO model(id,brand_id,name) VALUES (361,89,'PICAPE MONTEZ');
INSERT INTO model(id,brand_id,name) VALUES (362,16,'BESTA');
INSERT INTO model(id,brand_id,name) VALUES (363,16,'BONGO');
INSERT INTO model(id,brand_id,name) VALUES (364,16,'CADENZA');
INSERT INTO model(id,brand_id,name) VALUES (365,16,'CARENS');
INSERT INTO model(id,brand_id,name) VALUES (366,16,'CARNIVAL');
INSERT INTO model(id,brand_id,name) VALUES (367,16,'CERATO');
INSERT INTO model(id,brand_id,name) VALUES (368,16,'CERES');
INSERT INTO model(id,brand_id,name) VALUES (369,16,'CLARUS');
INSERT INTO model(id,brand_id,name) VALUES (370,16,'MAGENTIS');
INSERT INTO model(id,brand_id,name) VALUES (371,16,'MOHAVE');
INSERT INTO model(id,brand_id,name) VALUES (372,16,'OPIRUS');
INSERT INTO model(id,brand_id,name) VALUES (373,16,'OPTIMA');
INSERT INTO model(id,brand_id,name) VALUES (374,16,'PICANTO');
INSERT INTO model(id,brand_id,name) VALUES (375,16,'SEPHIA');
INSERT INTO model(id,brand_id,name) VALUES (376,16,'SHUMA');
INSERT INTO model(id,brand_id,name) VALUES (377,16,'SORENTO');
INSERT INTO model(id,brand_id,name) VALUES (378,16,'SOUL');
INSERT INTO model(id,brand_id,name) VALUES (379,16,'SPORTAGE');
INSERT INTO model(id,brand_id,name) VALUES (380,94,'LAIKA');
INSERT INTO model(id,brand_id,name) VALUES (381,94,'NIVA');
INSERT INTO model(id,brand_id,name) VALUES (382,94,'SAMARA');
INSERT INTO model(id,brand_id,name) VALUES (383,12,'GALLARDO');
INSERT INTO model(id,brand_id,name) VALUES (384,12,'MURCIELAGO');
INSERT INTO model(id,brand_id,name) VALUES (385,96,'DEFENDER');
INSERT INTO model(id,brand_id,name) VALUES (386,96,'DISCOVERY');
INSERT INTO model(id,brand_id,name) VALUES (389,96,'FREELANDER');
INSERT INTO model(id,brand_id,name) VALUES (391,96,'NEW RANGE');
INSERT INTO model(id,brand_id,name) VALUES (392,96,'RANGE ROVER');
INSERT INTO model(id,brand_id,name) VALUES (393,97,'ES');
INSERT INTO model(id,brand_id,name) VALUES (396,97,'GS');
INSERT INTO model(id,brand_id,name) VALUES (397,97,'IS-300');
INSERT INTO model(id,brand_id,name) VALUES (398,97,'LS');
INSERT INTO model(id,brand_id,name) VALUES (400,97,'RX');
INSERT INTO model(id,brand_id,name) VALUES (402,97,'SC');
INSERT INTO model(id,brand_id,name) VALUES (403,98,'320');
INSERT INTO model(id,brand_id,name) VALUES (404,98,'620');
INSERT INTO model(id,brand_id,name) VALUES (405,100,'H1');
INSERT INTO model(id,brand_id,name) VALUES (406,101,'ELAN');
INSERT INTO model(id,brand_id,name) VALUES (407,101,'ESPRIT');
INSERT INTO model(id,brand_id,name) VALUES (408,102,'SCORPIO');
INSERT INTO model(id,brand_id,name) VALUES (409,104,'222');
INSERT INTO model(id,brand_id,name) VALUES (410,104,'228');
INSERT INTO model(id,brand_id,name) VALUES (411,104,'3200');
INSERT INTO model(id,brand_id,name) VALUES (412,104,'430');
INSERT INTO model(id,brand_id,name) VALUES (413,104,'COUPE');
INSERT INTO model(id,brand_id,name) VALUES (414,104,'GHIBLI');
INSERT INTO model(id,brand_id,name) VALUES (415,104,'GRANCABRIO');
INSERT INTO model(id,brand_id,name) VALUES (416,104,'GRANSPORT');
INSERT INTO model(id,brand_id,name) VALUES (417,104,'GRANTURISMO');
INSERT INTO model(id,brand_id,name) VALUES (418,104,'QUATTROPORTE');
INSERT INTO model(id,brand_id,name) VALUES (419,104,'SHAMAL');
INSERT INTO model(id,brand_id,name) VALUES (420,104,'SPidER');
INSERT INTO model(id,brand_id,name) VALUES (422,106,'PICK-UP');
INSERT INTO model(id,brand_id,name) VALUES (423,108,'323');
INSERT INTO model(id,brand_id,name) VALUES (424,108,'626');
INSERT INTO model(id,brand_id,name) VALUES (425,108,'929');
INSERT INTO model(id,brand_id,name) VALUES (426,108,'B-2500');
INSERT INTO model(id,brand_id,name) VALUES (427,108,'B2200');
INSERT INTO model(id,brand_id,name) VALUES (428,108,'MILLENIA');
INSERT INTO model(id,brand_id,name) VALUES (429,108,'MPV');
INSERT INTO model(id,brand_id,name) VALUES (430,108,'MX-3');
INSERT INTO model(id,brand_id,name) VALUES (431,108,'MX-5');
INSERT INTO model(id,brand_id,name) VALUES (432,108,'NAVAJO');
INSERT INTO model(id,brand_id,name) VALUES (433,108,'PROTEGE');
INSERT INTO model(id,brand_id,name) VALUES (434,108,'RX');
INSERT INTO model(id,brand_id,name) VALUES (467,4,'CLASSE A');
INSERT INTO model(id,brand_id,name) VALUES (468,4,'CLASSE B');
INSERT INTO model(id,brand_id,name) VALUES (469,4,'CLASSE R');
INSERT INTO model(id,brand_id,name) VALUES (498,4,'CLASSE GLK');
INSERT INTO model(id,brand_id,name) VALUES (531,4,'SPRINTER');
INSERT INTO model(id,brand_id,name) VALUES (532,110,'MYSTIQUE');
INSERT INTO model(id,brand_id,name) VALUES (533,110,'SABLE');
INSERT INTO model(id,brand_id,name) VALUES (534,112,'550');
INSERT INTO model(id,brand_id,name) VALUES (535,112,'MG6');
INSERT INTO model(id,brand_id,name) VALUES (536,113,'COOPER');
INSERT INTO model(id,brand_id,name) VALUES (537,113,'ONE');
INSERT INTO model(id,brand_id,name) VALUES (538,111,'3000');
INSERT INTO model(id,brand_id,name) VALUES (539,111,'AIRTREK');
INSERT INTO model(id,brand_id,name) VALUES (540,111,'ASX');
INSERT INTO model(id,brand_id,name) VALUES (541,111,'COLT');
INSERT INTO model(id,brand_id,name) VALUES (542,111,'DIAMANT');
INSERT INTO model(id,brand_id,name) VALUES (543,111,'ECLIPSE');
INSERT INTO model(id,brand_id,name) VALUES (544,111,'EXPO');
INSERT INTO model(id,brand_id,name) VALUES (545,111,'GALANT');
INSERT INTO model(id,brand_id,name) VALUES (546,111,'GRANDIS');
INSERT INTO model(id,brand_id,name) VALUES (547,111,'L200');
INSERT INTO model(id,brand_id,name) VALUES (548,111,'L300');
INSERT INTO model(id,brand_id,name) VALUES (549,111,'LANCER');
INSERT INTO model(id,brand_id,name) VALUES (550,111,'MIRAGE');
INSERT INTO model(id,brand_id,name) VALUES (551,111,'MONTERO');
INSERT INTO model(id,brand_id,name) VALUES (552,111,'OUTLANDER');
INSERT INTO model(id,brand_id,name) VALUES (553,111,'PAJERO');
INSERT INTO model(id,brand_id,name) VALUES (554,111,'SPACE WAGON');
INSERT INTO model(id,brand_id,name) VALUES (555,114,'BG-TRUCK');
INSERT INTO model(id,brand_id,name) VALUES (556,43,'350Z');
INSERT INTO model(id,brand_id,name) VALUES (557,43,'ALTIMA');
INSERT INTO model(id,brand_id,name) VALUES (558,43,'AX');
INSERT INTO model(id,brand_id,name) VALUES (559,43,'D-21');
INSERT INTO model(id,brand_id,name) VALUES (560,43,'FRONTIER');
INSERT INTO model(id,brand_id,name) VALUES (562,43,'KING-CAB');
INSERT INTO model(id,brand_id,name) VALUES (563,43,'LIVINA');
INSERT INTO model(id,brand_id,name) VALUES (564,43,'MARCH');
INSERT INTO model(id,brand_id,name) VALUES (565,43,'MAXIMA');
INSERT INTO model(id,brand_id,name) VALUES (567,43,'MURANO');
INSERT INTO model(id,brand_id,name) VALUES (568,43,'NX');
INSERT INTO model(id,brand_id,name) VALUES (569,43,'PATHFINDER');
INSERT INTO model(id,brand_id,name) VALUES (571,43,'PRIMERA');
INSERT INTO model(id,brand_id,name) VALUES (572,43,'QUEST');
INSERT INTO model(id,brand_id,name) VALUES (573,43,'SENTRA');
INSERT INTO model(id,brand_id,name) VALUES (574,43,'STANZA');
INSERT INTO model(id,brand_id,name) VALUES (575,43,'180SX');
INSERT INTO model(id,brand_id,name) VALUES (576,43,'TERRANO');
INSERT INTO model(id,brand_id,name) VALUES (577,43,'TIidA');
INSERT INTO model(id,brand_id,name) VALUES (578,43,'VERSA');
INSERT INTO model(id,brand_id,name) VALUES (579,43,'X-TRAIL');
INSERT INTO model(id,brand_id,name) VALUES (580,43,'XTERRA');
INSERT INTO model(id,brand_id,name) VALUES (581,43,'ZX');
INSERT INTO model(id,brand_id,name) VALUES (582,22,'106');
INSERT INTO model(id,brand_id,name) VALUES (583,22,'205');
INSERT INTO model(id,brand_id,name) VALUES (584,22,'206');
INSERT INTO model(id,brand_id,name) VALUES (585,22,'207');
INSERT INTO model(id,brand_id,name) VALUES (586,22,'3008');
INSERT INTO model(id,brand_id,name) VALUES (587,22,'306');
INSERT INTO model(id,brand_id,name) VALUES (588,22,'307');
INSERT INTO model(id,brand_id,name) VALUES (589,22,'308');
INSERT INTO model(id,brand_id,name) VALUES (590,22,'405');
INSERT INTO model(id,brand_id,name) VALUES (591,22,'406');
INSERT INTO model(id,brand_id,name) VALUES (592,22,'407');
INSERT INTO model(id,brand_id,name) VALUES (593,22,'408');
INSERT INTO model(id,brand_id,name) VALUES (594,22,'504');
INSERT INTO model(id,brand_id,name) VALUES (595,22,'505');
INSERT INTO model(id,brand_id,name) VALUES (596,22,'508');
INSERT INTO model(id,brand_id,name) VALUES (597,22,'605');
INSERT INTO model(id,brand_id,name) VALUES (598,22,'607');
INSERT INTO model(id,brand_id,name) VALUES (599,22,'806');
INSERT INTO model(id,brand_id,name) VALUES (600,22,'807');
INSERT INTO model(id,brand_id,name) VALUES (601,22,'BOXER');
INSERT INTO model(id,brand_id,name) VALUES (602,22,'HOGGAR');
INSERT INTO model(id,brand_id,name) VALUES (603,22,'PARTNER');
INSERT INTO model(id,brand_id,name) VALUES (604,22,'RCZ');
INSERT INTO model(id,brand_id,name) VALUES (605,123,'GRAN VOYAGER');
INSERT INTO model(id,brand_id,name) VALUES (606,123,'SUNDANCE');
INSERT INTO model(id,brand_id,name) VALUES (607,69,'TRANS-AM');
INSERT INTO model(id,brand_id,name) VALUES (608,69,'TRANS-SPORT');
INSERT INTO model(id,brand_id,name) VALUES (609,70,'911');
INSERT INTO model(id,brand_id,name) VALUES (612,70,'BOXSTER');
INSERT INTO model(id,brand_id,name) VALUES (613,70,'CAYENNE');
INSERT INTO model(id,brand_id,name) VALUES (614,70,'CAYMAN');
INSERT INTO model(id,brand_id,name) VALUES (615,70,'PANAMERA');
INSERT INTO model(id,brand_id,name) VALUES (617,24,'21 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (618,24,'CLIO');
INSERT INTO model(id,brand_id,name) VALUES (619,24,'DUSTER');
INSERT INTO model(id,brand_id,name) VALUES (620,24,'EXPRESS');
INSERT INTO model(id,brand_id,name) VALUES (621,24,'FLUENCE');
INSERT INTO model(id,brand_id,name) VALUES (622,24,'KANGOO');
INSERT INTO model(id,brand_id,name) VALUES (623,24,'LAGUNA');
INSERT INTO model(id,brand_id,name) VALUES (624,24,'LOGAN');
INSERT INTO model(id,brand_id,name) VALUES (625,24,'MASTER');
INSERT INTO model(id,brand_id,name) VALUES (626,24,'MEGANE');
INSERT INTO model(id,brand_id,name) VALUES (627,24,'SAFRANE');
INSERT INTO model(id,brand_id,name) VALUES (628,24,'SANDERO');
INSERT INTO model(id,brand_id,name) VALUES (629,24,'SCENIC');
INSERT INTO model(id,brand_id,name) VALUES (630,24,'SYMBOL');
INSERT INTO model(id,brand_id,name) VALUES (631,24,'TRAFIC');
INSERT INTO model(id,brand_id,name) VALUES (632,24,'TWINGO');
INSERT INTO model(id,brand_id,name) VALUES (634,137,'9000');
INSERT INTO model(id,brand_id,name) VALUES (635,162,'SL-2');
INSERT INTO model(id,brand_id,name) VALUES (636,130,'CORDOBA');
INSERT INTO model(id,brand_id,name) VALUES (637,130,'IBIZA');
INSERT INTO model(id,brand_id,name) VALUES (638,130,'INCA');
INSERT INTO model(id,brand_id,name) VALUES (641,142,'FORTWO');
INSERT INTO model(id,brand_id,name) VALUES (642,21,'ACTYON SPORTS');
INSERT INTO model(id,brand_id,name) VALUES (643,21,'CHAIRMAN');
INSERT INTO model(id,brand_id,name) VALUES (644,21,'ISTANA');
INSERT INTO model(id,brand_id,name) VALUES (645,21,'KORANDO');
INSERT INTO model(id,brand_id,name) VALUES (646,21,'KYRON');
INSERT INTO model(id,brand_id,name) VALUES (647,21,'MUSSO');
INSERT INTO model(id,brand_id,name) VALUES (648,21,'REXTON');
INSERT INTO model(id,brand_id,name) VALUES (649,8,'FORESTER');
INSERT INTO model(id,brand_id,name) VALUES (650,8,'IMPREZA');
INSERT INTO model(id,brand_id,name) VALUES (651,8,'LEGACY');
INSERT INTO model(id,brand_id,name) VALUES (652,8,'OUTBACK');
INSERT INTO model(id,brand_id,name) VALUES (653,8,'SVX');
INSERT INTO model(id,brand_id,name) VALUES (654,8,'TRIBECA');
INSERT INTO model(id,brand_id,name) VALUES (655,8,'VIVIO');
INSERT INTO model(id,brand_id,name) VALUES (656,59,'BALENO');
INSERT INTO model(id,brand_id,name) VALUES (657,59,'GRAND VITARA');
INSERT INTO model(id,brand_id,name) VALUES (658,59,'IGNIS');
INSERT INTO model(id,brand_id,name) VALUES (660,59,'JIMNY');
INSERT INTO model(id,brand_id,name) VALUES (662,59,'SUPER CARRY');
INSERT INTO model(id,brand_id,name) VALUES (663,59,'SWIFT');
INSERT INTO model(id,brand_id,name) VALUES (664,59,'SX4');
INSERT INTO model(id,brand_id,name) VALUES (665,59,'VITARA');
INSERT INTO model(id,brand_id,name) VALUES (666,59,'WAGON R');
INSERT INTO model(id,brand_id,name) VALUES (667,146,'STARK');
INSERT INTO model(id,brand_id,name) VALUES (668,23,'AVALON');
INSERT INTO model(id,brand_id,name) VALUES (669,23,'BANDEIRANTE');
INSERT INTO model(id,brand_id,name) VALUES (670,23,'CAMRY');
INSERT INTO model(id,brand_id,name) VALUES (671,23,'CELICA');
INSERT INTO model(id,brand_id,name) VALUES (672,23,'COROLLA');
INSERT INTO model(id,brand_id,name) VALUES (673,23,'CORONA');
INSERT INTO model(id,brand_id,name) VALUES (674,23,'HILUX');
INSERT INTO model(id,brand_id,name) VALUES (675,23,'LAND CRUISER');
INSERT INTO model(id,brand_id,name) VALUES (676,23,'MR-2');
INSERT INTO model(id,brand_id,name) VALUES (677,23,'PASEO');
INSERT INTO model(id,brand_id,name) VALUES (678,23,'PREVIA');
INSERT INTO model(id,brand_id,name) VALUES (679,23,'RAV4');
INSERT INTO model(id,brand_id,name) VALUES (680,23,'SUPRA');
INSERT INTO model(id,brand_id,name) VALUES (682,149,'PANTANAL');
INSERT INTO model(id,brand_id,name) VALUES (684,149,'T-4');
INSERT INTO model(id,brand_id,name) VALUES (685,53,'400 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (687,53,'850');
INSERT INTO model(id,brand_id,name) VALUES (688,53,'900 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (700,2,'AMAROK');
INSERT INTO model(id,brand_id,name) VALUES (701,2,'APOLLO');
INSERT INTO model(id,brand_id,name) VALUES (702,2,'BORA');
INSERT INTO model(id,brand_id,name) VALUES (703,2,'CARAVELLE');
INSERT INTO model(id,brand_id,name) VALUES (704,2,'CORRADO');
INSERT INTO model(id,brand_id,name) VALUES (706,2,'EOS');
INSERT INTO model(id,brand_id,name) VALUES (707,2,'EUROVAN');
INSERT INTO model(id,brand_id,name) VALUES (708,2,'FOX');
INSERT INTO model(id,brand_id,name) VALUES (709,2,'FUSCA');
INSERT INTO model(id,brand_id,name) VALUES (710,2,'GOL');
INSERT INTO model(id,brand_id,name) VALUES (711,2,'GOLF');
INSERT INTO model(id,brand_id,name) VALUES (713,2,'JETTA');
INSERT INTO model(id,brand_id,name) VALUES (714,2,'KOMBI');
INSERT INTO model(id,brand_id,name) VALUES (715,2,'LOGUS');
INSERT INTO model(id,brand_id,name) VALUES (717,2,'PARATI');
INSERT INTO model(id,brand_id,name) VALUES (718,2,'PASSAT');
INSERT INTO model(id,brand_id,name) VALUES (719,2,'POINTER');
INSERT INTO model(id,brand_id,name) VALUES (720,2,'POLO');
INSERT INTO model(id,brand_id,name) VALUES (722,2,'SANTANA');
INSERT INTO model(id,brand_id,name) VALUES (723,2,'SAVEIRO');
INSERT INTO model(id,brand_id,name) VALUES (725,2,'SPACEFOX');
INSERT INTO model(id,brand_id,name) VALUES (726,2,'TIGUAN');
INSERT INTO model(id,brand_id,name) VALUES (727,2,'TOUAREG');
INSERT INTO model(id,brand_id,name) VALUES (729,2,'VOYAGE');
INSERT INTO model(id,brand_id,name) VALUES (732,25,'ZDX');
INSERT INTO model(id,brand_id,name) VALUES (737,3,'140');
INSERT INTO model(id,brand_id,name) VALUES (755,2,'BRASILIA');
INSERT INTO model(id,brand_id,name) VALUES (756,13,'BRASILVAN');
INSERT INTO model(id,brand_id,name) VALUES (775,13,'CORCEL');
INSERT INTO model(id,brand_id,name) VALUES (803,3,'PALIO WEEKEND');
INSERT INTO model(id,brand_id,name) VALUES (806,13,'FOCUS SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (807,13,'FIESTA SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (808,13,'FIESTA TRAIL');
INSERT INTO model(id,brand_id,name) VALUES (810,22,'207 SW');
INSERT INTO model(id,brand_id,name) VALUES (811,13,'ESCORT SW');
INSERT INTO model(id,brand_id,name) VALUES (812,22,'307 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (813,22,'307 SW');
INSERT INTO model(id,brand_id,name) VALUES (815,5,'C4 PALLAS');
INSERT INTO model(id,brand_id,name) VALUES (816,5,'C4 PICASSO');
INSERT INTO model(id,brand_id,name) VALUES (817,5,'C4 VTR');
INSERT INTO model(id,brand_id,name) VALUES (818,24,'CLIO SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (819,23,'COROLLA FIELDER');
INSERT INTO model(id,brand_id,name) VALUES (824,23,'HILUX SW4');
INSERT INTO model(id,brand_id,name) VALUES (825,24,'MEGANE GRAND TOUR');
INSERT INTO model(id,brand_id,name) VALUES (827,24,'SANDERO STEPWAY');
INSERT INTO model(id,brand_id,name) VALUES (829,5,'XSARA PICASSO');
INSERT INTO model(id,brand_id,name) VALUES (1360,131,'COLHEITADEIRA');
INSERT INTO model(id,brand_id,name) VALUES (1361,158,'PICKUP F75');
INSERT INTO model(id,brand_id,name) VALUES (1362,17,'X12');
INSERT INTO model(id,brand_id,name) VALUES (1365,1,'BEL AIR');
INSERT INTO model(id,brand_id,name) VALUES (1366,36,'RX');
INSERT INTO model(id,brand_id,name) VALUES (1369,1,'C-14');
INSERT INTO model(id,brand_id,name) VALUES (1370,155,'SRX4');
INSERT INTO model(id,brand_id,name) VALUES (1372,1,'C-15');
INSERT INTO model(id,brand_id,name) VALUES (1373,1,'BRASIL');
INSERT INTO model(id,brand_id,name) VALUES (1377,18,'POLARA');
INSERT INTO model(id,brand_id,name) VALUES (1380,3,'600');
INSERT INTO model(id,brand_id,name) VALUES (1382,13,'F-01');
INSERT INTO model(id,brand_id,name) VALUES (1383,13,'FALCON');
INSERT INTO model(id,brand_id,name) VALUES (1384,13,'GALAXIE');
INSERT INTO model(id,brand_id,name) VALUES (1386,13,'MAVERICK');
INSERT INTO model(id,brand_id,name) VALUES (1387,13,'MODELO A');
INSERT INTO model(id,brand_id,name) VALUES (1388,13,'NEW FIESTA');
INSERT INTO model(id,brand_id,name) VALUES (1389,82,'LINHA FX');
INSERT INTO model(id,brand_id,name) VALUES (1391,124,'GTS');
INSERT INTO model(id,brand_id,name) VALUES (1392,80,'H3');
INSERT INTO model(id,brand_id,name) VALUES (1394,14,'PRIME');
INSERT INTO model(id,brand_id,name) VALUES (1395,14,'TIBURON');
INSERT INTO model(id,brand_id,name) VALUES (1397,87,'JEEP');
INSERT INTO model(id,brand_id,name) VALUES (1398,87,'CJ5');
INSERT INTO model(id,brand_id,name) VALUES (1399,239,'TC');
INSERT INTO model(id,brand_id,name) VALUES (1404,4,'CLASSE CLC');
INSERT INTO model(id,brand_id,name) VALUES (1405,4,'CLASSE CLS');
INSERT INTO model(id,brand_id,name) VALUES (1408,110,'MONTEREY');
INSERT INTO model(id,brand_id,name) VALUES (1411,114,'TOPSPORT');
INSERT INTO model(id,brand_id,name) VALUES (1412,114,'TARGA');
INSERT INTO model(id,brand_id,name) VALUES (1414,114,'X8');
INSERT INTO model(id,brand_id,name) VALUES (1415,43,'370Z');
INSERT INTO model(id,brand_id,name) VALUES (1418,124,'GTB');
INSERT INTO model(id,brand_id,name) VALUES (1419,124,'GTC');
INSERT INTO model(id,brand_id,name) VALUES (1420,124,'GTE');
INSERT INTO model(id,brand_id,name) VALUES (1421,115,'AUSTIN');
INSERT INTO model(id,brand_id,name) VALUES (1423,24,'7TL');
INSERT INTO model(id,brand_id,name) VALUES (1424,24,'19');
INSERT INTO model(id,brand_id,name) VALUES (1426,175,'CONVERSÍVEL');
INSERT INTO model(id,brand_id,name) VALUES (1427,17,'SUPERMINI');
INSERT INTO model(id,brand_id,name) VALUES (1428,2,'TL');
INSERT INTO model(id,brand_id,name) VALUES (1429,3,'TOPOLINO');
INSERT INTO model(id,brand_id,name) VALUES (1430,23,'SR5');
INSERT INTO model(id,brand_id,name) VALUES (1431,23,'VITZ');
INSERT INTO model(id,brand_id,name) VALUES (1432,2,'VARIANT');
INSERT INTO model(id,brand_id,name) VALUES (1454,57,'CANDANGO');
INSERT INTO model(id,brand_id,name) VALUES (1460,2,'SP2');
INSERT INTO model(id,brand_id,name) VALUES (1466,258,'RECORB');
INSERT INTO model(id,brand_id,name) VALUES (1467,2,'POLAUTO');
INSERT INTO model(id,brand_id,name) VALUES (1508,24,'GORDINI');
INSERT INTO model(id,brand_id,name) VALUES (1509,265,'MINX');
INSERT INTO model(id,brand_id,name) VALUES (1971,23,'ETIOS');
INSERT INTO model(id,brand_id,name) VALUES (1972,1,'ONIX');
INSERT INTO model(id,brand_id,name) VALUES (1973,14,'HB20');
INSERT INTO model(id,brand_id,name) VALUES (1975,36,'330');
INSERT INTO model(id,brand_id,name) VALUES (1976,36,'520');
INSERT INTO model(id,brand_id,name) VALUES (1978,36,'730');
INSERT INTO model(id,brand_id,name) VALUES (1980,36,'M1');
INSERT INTO model(id,brand_id,name) VALUES (1982,36,'SERIE Z');
INSERT INTO model(id,brand_id,name) VALUES (1983,4,'CLASSE SLK');
INSERT INTO model(id,brand_id,name) VALUES (1984,4,'CLASSE C');
INSERT INTO model(id,brand_id,name) VALUES (1985,4,'CLASSE E');
INSERT INTO model(id,brand_id,name) VALUES (1986,4,'CLASSE CL');
INSERT INTO model(id,brand_id,name) VALUES (1987,4,'CLASSE CLK');
INSERT INTO model(id,brand_id,name) VALUES (1988,4,'CLASSE S');
INSERT INTO model(id,brand_id,name) VALUES (1989,4,'CLASSE SL');
INSERT INTO model(id,brand_id,name) VALUES (1990,4,'CLASSE SLS');
INSERT INTO model(id,brand_id,name) VALUES (1991,4,'CLASSE G');
INSERT INTO model(id,brand_id,name) VALUES (1992,4,'CLASSE GL');
INSERT INTO model(id,brand_id,name) VALUES (1993,4,'CLASSE M');
INSERT INTO model(id,brand_id,name) VALUES (2032,288,'1500');
INSERT INTO model(id,brand_id,name) VALUES (2061,14,'EQUUS');
INSERT INTO model(id,brand_id,name) VALUES (2067,12,'350 GT');
INSERT INTO model(id,brand_id,name) VALUES (2068,12,'400 GT');
INSERT INTO model(id,brand_id,name) VALUES (2069,12,'MIURA');
INSERT INTO model(id,brand_id,name) VALUES (2070,12,'ISLERO');
INSERT INTO model(id,brand_id,name) VALUES (2071,12,'ESPADA');
INSERT INTO model(id,brand_id,name) VALUES (2072,12,'COUNTACH');
INSERT INTO model(id,brand_id,name) VALUES (2073,12,'DIABLO');
INSERT INTO model(id,brand_id,name) VALUES (2074,12,'ZAGATO');
INSERT INTO model(id,brand_id,name) VALUES (2075,12,'ALAR');
INSERT INTO model(id,brand_id,name) VALUES (2076,12,'LM002');
INSERT INTO model(id,brand_id,name) VALUES (2077,12,'REVENTON');
INSERT INTO model(id,brand_id,name) VALUES (2078,12,'ANKONIAN');
INSERT INTO model(id,brand_id,name) VALUES (2080,12,'AVENTADOR');
INSERT INTO model(id,brand_id,name) VALUES (2081,12,'SESTO ELEMENTO');
INSERT INTO model(id,brand_id,name) VALUES (2082,15,'J3 TURIN');
INSERT INTO model(id,brand_id,name) VALUES (2083,15,'J2');
INSERT INTO model(id,brand_id,name) VALUES (2084,24,'SANDERO GT');
INSERT INTO model(id,brand_id,name) VALUES (2087,1,'SPIN');
INSERT INTO model(id,brand_id,name) VALUES (2088,1,'TRAILBLAZER');
INSERT INTO model(id,brand_id,name) VALUES (2097,5,'C3 PICASSO');
INSERT INTO model(id,brand_id,name) VALUES (2098,5,'GRAND C4 PICASSO');
INSERT INTO model(id,brand_id,name) VALUES (2099,5,'JUMPER MINIBUS');
INSERT INTO model(id,brand_id,name) VALUES (2100,5,'JUMPER VETRATO');
INSERT INTO model(id,brand_id,name) VALUES (2101,22,'207 SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2102,22,'207 QUIKSILVER');
INSERT INTO model(id,brand_id,name) VALUES (2103,22,'207 ESCAPADE');
INSERT INTO model(id,brand_id,name) VALUES (2104,22,'308 CC');
INSERT INTO model(id,brand_id,name) VALUES (2105,22,'BOXER PASSAGEIRO');
INSERT INTO model(id,brand_id,name) VALUES (2106,13,'NEW FIESTA SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2108,13,'TRANSIT PASSAGEIRO');
INSERT INTO model(id,brand_id,name) VALUES (2109,13,'TRANSIT CHASSI');
INSERT INTO model(id,brand_id,name) VALUES (2110,32,'A4 AVANT');
INSERT INTO model(id,brand_id,name) VALUES (2111,32,'S4 AVANT');
INSERT INTO model(id,brand_id,name) VALUES (2112,32,'A5 SPORTBACK');
INSERT INTO model(id,brand_id,name) VALUES (2113,32,'A5 CABRIOLET');
INSERT INTO model(id,brand_id,name) VALUES (2114,32,'S5 COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2115,32,'S5 SPORTBACK');
INSERT INTO model(id,brand_id,name) VALUES (2116,32,'S5 CABRIOLET');
INSERT INTO model(id,brand_id,name) VALUES (2117,32,'A6 AVANT');
INSERT INTO model(id,brand_id,name) VALUES (2118,32,'A6 ALLROAD');
INSERT INTO model(id,brand_id,name) VALUES (2119,32,'S6 AVANT');
INSERT INTO model(id,brand_id,name) VALUES (2120,32,'S7');
INSERT INTO model(id,brand_id,name) VALUES (2121,32,'TT ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (2122,32,'TT RS');
INSERT INTO model(id,brand_id,name) VALUES (2123,32,'TT RS ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (2124,32,'TTS ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (2125,32,'R8 SPYDER');
INSERT INTO model(id,brand_id,name) VALUES (2126,32,'R8 GT');
INSERT INTO model(id,brand_id,name) VALUES (2127,32,'R8 GT SPYDER');
INSERT INTO model(id,brand_id,name) VALUES (2129,10,'F12');
INSERT INTO model(id,brand_id,name) VALUES (2130,10,'458 SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2131,10,'458 ITALIA');
INSERT INTO model(id,brand_id,name) VALUES (2132,10,'FF');
INSERT INTO model(id,brand_id,name) VALUES (2133,10,'599');
INSERT INTO model(id,brand_id,name) VALUES (2134,10,'SA');
INSERT INTO model(id,brand_id,name) VALUES (2135,10,'CHALLENGE');
INSERT INTO model(id,brand_id,name) VALUES (2136,10,'SUPERAMERICA');
INSERT INTO model(id,brand_id,name) VALUES (2137,10,'F430 SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2138,10,'430');
INSERT INTO model(id,brand_id,name) VALUES (2139,10,'612 SESSANTA');
INSERT INTO model(id,brand_id,name) VALUES (2140,10,'599 GTB');
INSERT INTO model(id,brand_id,name) VALUES (2141,10,'SCUDERIA SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2142,10,'512');
INSERT INTO model(id,brand_id,name) VALUES (2143,10,'456 GT');
INSERT INTO model(id,brand_id,name) VALUES (2144,10,'348 GTS');
INSERT INTO model(id,brand_id,name) VALUES (2145,10,'348 SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2146,10,'F355');
INSERT INTO model(id,brand_id,name) VALUES (2147,10,'F355 SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2148,10,'F50');
INSERT INTO model(id,brand_id,name) VALUES (2149,10,'355 SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2150,10,'360 MODENA');
INSERT INTO model(id,brand_id,name) VALUES (2151,111,'PAJERO FULL');
INSERT INTO model(id,brand_id,name) VALUES (2152,111,'PAJERO DAKAR');
INSERT INTO model(id,brand_id,name) VALUES (2153,111,'PAJERO TR4');
INSERT INTO model(id,brand_id,name) VALUES (2154,111,'LANCER SPORTBACK');
INSERT INTO model(id,brand_id,name) VALUES (2155,111,'LANCER EVOLUTION');
INSERT INTO model(id,brand_id,name) VALUES (2156,111,'L200 TRITON SAVANA');
INSERT INTO model(id,brand_id,name) VALUES (2157,111,'L200 TRITON');
INSERT INTO model(id,brand_id,name) VALUES (2159,43,'LIVINA X-GEAR');
INSERT INTO model(id,brand_id,name) VALUES (2160,43,'GRAND LIVINA');
INSERT INTO model(id,brand_id,name) VALUES (2161,21,'NEW ACTYON SPORTS');
INSERT INTO model(id,brand_id,name) VALUES (2162,23,'PRIUS');
INSERT INTO model(id,brand_id,name) VALUES (2163,114,'SPORT');
INSERT INTO model(id,brand_id,name) VALUES (2164,114,'MTS');
INSERT INTO model(id,brand_id,name) VALUES (2165,114,'SPidER');
INSERT INTO model(id,brand_id,name) VALUES (2166,114,'KABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2167,114,'SAGA');
INSERT INTO model(id,brand_id,name) VALUES (2168,114,'SAGA II');
INSERT INTO model(id,brand_id,name) VALUES (2169,114,'787');
INSERT INTO model(id,brand_id,name) VALUES (2170,114,'X11');
INSERT INTO model(id,brand_id,name) VALUES (2171,295,'GAIOLA');
INSERT INTO model(id,brand_id,name) VALUES (2175,18,'NITRO');
INSERT INTO model(id,brand_id,name) VALUES (2176,18,'CHALLENGER');
INSERT INTO model(id,brand_id,name) VALUES (2177,18,'DART');
INSERT INTO model(id,brand_id,name) VALUES (2178,18,'LE BARON');
INSERT INTO model(id,brand_id,name) VALUES (2179,18,'CORDOBA');
INSERT INTO model(id,brand_id,name) VALUES (2180,18,'CHARGER');
INSERT INTO model(id,brand_id,name) VALUES (2181,19,'WINDSOR');
INSERT INTO model(id,brand_id,name) VALUES (2183,19,'CROSSFIRE');
INSERT INTO model(id,brand_id,name) VALUES (2184,19,'CORDOBA');
INSERT INTO model(id,brand_id,name) VALUES (2185,155,'ESCALADE');
INSERT INTO model(id,brand_id,name) VALUES (2186,41,'RIVIERA');
INSERT INTO model(id,brand_id,name) VALUES (2187,41,'COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2188,41,'CENTURY');
INSERT INTO model(id,brand_id,name) VALUES (2189,41,'APOLLO');
INSERT INTO model(id,brand_id,name) VALUES (2190,41,'CENTURION');
INSERT INTO model(id,brand_id,name) VALUES (2191,41,'EIGHT');
INSERT INTO model(id,brand_id,name) VALUES (2192,41,'ELECTRA');
INSERT INTO model(id,brand_id,name) VALUES (2193,41,'ESTATE WAGON');
INSERT INTO model(id,brand_id,name) VALUES (2194,41,'GRAN SPORT');
INSERT INTO model(id,brand_id,name) VALUES (2195,41,'GSX');
INSERT INTO model(id,brand_id,name) VALUES (2196,41,'INVICTA');
INSERT INTO model(id,brand_id,name) VALUES (2197,41,'LESABRE');
INSERT INTO model(id,brand_id,name) VALUES (2198,41,'LIMITED');
INSERT INTO model(id,brand_id,name) VALUES (2199,41,'PARK AVENUE');
INSERT INTO model(id,brand_id,name) VALUES (2200,41,'RAINIER');
INSERT INTO model(id,brand_id,name) VALUES (2201,41,'REATTA');
INSERT INTO model(id,brand_id,name) VALUES (2202,41,'REGAL');
INSERT INTO model(id,brand_id,name) VALUES (2203,41,'RENDEZVOUS');
INSERT INTO model(id,brand_id,name) VALUES (2204,41,'ROADMASTER');
INSERT INTO model(id,brand_id,name) VALUES (2205,41,'ROYAUM');
INSERT INTO model(id,brand_id,name) VALUES (2206,41,'SKYHAWK');
INSERT INTO model(id,brand_id,name) VALUES (2207,41,'SKYLARK');
INSERT INTO model(id,brand_id,name) VALUES (2208,41,'SOMERSET');
INSERT INTO model(id,brand_id,name) VALUES (2209,41,'SPECIAL');
INSERT INTO model(id,brand_id,name) VALUES (2210,41,'SPORT WAGON');
INSERT INTO model(id,brand_id,name) VALUES (2211,41,'SUPER');
INSERT INTO model(id,brand_id,name) VALUES (2212,41,'TERRAZA');
INSERT INTO model(id,brand_id,name) VALUES (2213,41,'WILDCAT');
INSERT INTO model(id,brand_id,name) VALUES (2214,41,'LACROSSE');
INSERT INTO model(id,brand_id,name) VALUES (2215,41,'ENCLAVE');
INSERT INTO model(id,brand_id,name) VALUES (2217,41,'GL8');
INSERT INTO model(id,brand_id,name) VALUES (2218,41,'HRV');
INSERT INTO model(id,brand_id,name) VALUES (2219,41,'LUCERNE');
INSERT INTO model(id,brand_id,name) VALUES (2230,13,'SIERRA');
INSERT INTO model(id,brand_id,name) VALUES (2231,51,'BROUGHAM');
INSERT INTO model(id,brand_id,name) VALUES (2232,51,'CHAIRMAN');
INSERT INTO model(id,brand_id,name) VALUES (2233,51,'DAMAS');
INSERT INTO model(id,brand_id,name) VALUES (2234,51,'GENTRA');
INSERT INTO model(id,brand_id,name) VALUES (2235,51,'MAEPSY');
INSERT INTO model(id,brand_id,name) VALUES (2236,51,'ISTANA');
INSERT INTO model(id,brand_id,name) VALUES (2237,51,'KALOS');
INSERT INTO model(id,brand_id,name) VALUES (2238,51,'KORANDO');
INSERT INTO model(id,brand_id,name) VALUES (2239,51,'LACETTI');
INSERT INTO model(id,brand_id,name) VALUES (2240,51,'LEMANS');
INSERT INTO model(id,brand_id,name) VALUES (2242,51,'MATIZ');
INSERT INTO model(id,brand_id,name) VALUES (2243,51,'MUSSO');
INSERT INTO model(id,brand_id,name) VALUES (2244,51,'NEXIA');
INSERT INTO model(id,brand_id,name) VALUES (2245,51,'REZZO');
INSERT INTO model(id,brand_id,name) VALUES (2246,51,'ROYALE PRINCE');
INSERT INTO model(id,brand_id,name) VALUES (2247,51,'ROYALE SALON');
INSERT INTO model(id,brand_id,name) VALUES (2248,51,'STATESMAN');
INSERT INTO model(id,brand_id,name) VALUES (2249,51,'TOSCA');
INSERT INTO model(id,brand_id,name) VALUES (2250,51,'WINSTORM');
INSERT INTO model(id,brand_id,name) VALUES (2252,158,'RURAL');
INSERT INTO model(id,brand_id,name) VALUES (2253,18,'D100');
INSERT INTO model(id,brand_id,name) VALUES (2259,4,'170');
INSERT INTO model(id,brand_id,name) VALUES (2261,18,'CUSTOM ROYAL');
INSERT INTO model(id,brand_id,name) VALUES (2262,1,'CLUB COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2263,18,'MAGNUM');
INSERT INTO model(id,brand_id,name) VALUES (2264,1,'GMC 100');
INSERT INTO model(id,brand_id,name) VALUES (2265,69,'SOLSTICE');
INSERT INTO model(id,brand_id,name) VALUES (2266,158,'ITAMARATY');
INSERT INTO model(id,brand_id,name) VALUES (2267,86,'MARK V');
INSERT INTO model(id,brand_id,name) VALUES (2268,124,'GT');
INSERT INTO model(id,brand_id,name) VALUES (2269,145,'CHAMPION');
INSERT INTO model(id,brand_id,name) VALUES (2270,3,'BALILLA');
INSERT INTO model(id,brand_id,name) VALUES (2271,158,'INTERLAGOS');
INSERT INTO model(id,brand_id,name) VALUES (2272,17,'X15');
INSERT INTO model(id,brand_id,name) VALUES (2273,13,'F-85');
INSERT INTO model(id,brand_id,name) VALUES (2274,70,'SPEEDSTER 356');
INSERT INTO model(id,brand_id,name) VALUES (2275,88,'TOPIC FURGAO');
INSERT INTO model(id,brand_id,name) VALUES (2276,88,'TOPIC ESCOLAR');
INSERT INTO model(id,brand_id,name) VALUES (2279,4,'300D');
INSERT INTO model(id,brand_id,name) VALUES (2280,4,'CLASSE TE');
INSERT INTO model(id,brand_id,name) VALUES (2283,23,'T-100');
INSERT INTO model(id,brand_id,name) VALUES (2294,24,'MEGANE SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2295,32,'A4 CABRIOLET');
INSERT INTO model(id,brand_id,name) VALUES (2298,82,'LINHA G');
INSERT INTO model(id,brand_id,name) VALUES (2299,82,'LINHA G COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2300,82,'LINHA G CONVERSIVEL');
INSERT INTO model(id,brand_id,name) VALUES (2301,82,'LINHA M');
INSERT INTO model(id,brand_id,name) VALUES (2302,82,'LINHA EX');
INSERT INTO model(id,brand_id,name) VALUES (2303,82,'LINHA JX');
INSERT INTO model(id,brand_id,name) VALUES (2304,82,'LINHA QX');
INSERT INTO model(id,brand_id,name) VALUES (2305,86,'MODELOS XF');
INSERT INTO model(id,brand_id,name) VALUES (2306,86,'F-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (2307,86,'MARK VII');
INSERT INTO model(id,brand_id,name) VALUES (2308,86,'MARK VIII');
INSERT INTO model(id,brand_id,name) VALUES (2309,86,'MARK IX');
INSERT INTO model(id,brand_id,name) VALUES (2310,86,'MARK X');
INSERT INTO model(id,brand_id,name) VALUES (2311,86,'E-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (2312,86,'C-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (2313,86,'D-TYPE');
INSERT INTO model(id,brand_id,name) VALUES (2314,86,'MARK I');
INSERT INTO model(id,brand_id,name) VALUES (2315,86,'MARK II');
INSERT INTO model(id,brand_id,name) VALUES (2346,124,'GT4R');
INSERT INTO model(id,brand_id,name) VALUES (2347,124,'SPYDER');
INSERT INTO model(id,brand_id,name) VALUES (2348,124,'GTI');
INSERT INTO model(id,brand_id,name) VALUES (2349,124,'AM1');
INSERT INTO model(id,brand_id,name) VALUES (2350,124,'AM2');
INSERT INTO model(id,brand_id,name) VALUES (2351,124,'AM3');
INSERT INTO model(id,brand_id,name) VALUES (2352,124,'AM4');
INSERT INTO model(id,brand_id,name) VALUES (2353,124,'AMV');
INSERT INTO model(id,brand_id,name) VALUES (2377,7,'ACTY');
INSERT INTO model(id,brand_id,name) VALUES (2378,7,'AIRWAVE');
INSERT INTO model(id,brand_id,name) VALUES (2379,7,'ASCOT');
INSERT INTO model(id,brand_id,name) VALUES (2380,7,'BALLADE');
INSERT INTO model(id,brand_id,name) VALUES (2381,7,'BEAT');
INSERT INTO model(id,brand_id,name) VALUES (2382,7,'CR-X');
INSERT INTO model(id,brand_id,name) VALUES (2383,7,'CONCERTO');
INSERT INTO model(id,brand_id,name) VALUES (2384,7,'CR-Z');
INSERT INTO model(id,brand_id,name) VALUES (2385,7,'DOMANI');
INSERT INTO model(id,brand_id,name) VALUES (2386,7,'EDIX');
INSERT INTO model(id,brand_id,name) VALUES (2387,7,'ELEMENT');
INSERT INTO model(id,brand_id,name) VALUES (2388,7,'EV PLUS');
INSERT INTO model(id,brand_id,name) VALUES (2389,7,'FCX');
INSERT INTO model(id,brand_id,name) VALUES (2390,7,'FR-V');
INSERT INTO model(id,brand_id,name) VALUES (2392,7,'HR-V');
INSERT INTO model(id,brand_id,name) VALUES (2393,7,'HSC');
INSERT INTO model(id,brand_id,name) VALUES (2394,7,'INSIGHT');
INSERT INTO model(id,brand_id,name) VALUES (2396,25,'TL');
INSERT INTO model(id,brand_id,name) VALUES (2397,7,'LIFE DUNK');
INSERT INTO model(id,brand_id,name) VALUES (2398,7,'LOGO');
INSERT INTO model(id,brand_id,name) VALUES (2399,7,'MOBILIO');
INSERT INTO model(id,brand_id,name) VALUES (2400,25,'MDX');
INSERT INTO model(id,brand_id,name) VALUES (2401,7,'ORTHIA');
INSERT INTO model(id,brand_id,name) VALUES (2402,7,'PARTNER VAN');
INSERT INTO model(id,brand_id,name) VALUES (2403,7,'PILOT');
INSERT INTO model(id,brand_id,name) VALUES (2404,7,'RidGELINE');
INSERT INTO model(id,brand_id,name) VALUES (2405,7,'S2000');
INSERT INTO model(id,brand_id,name) VALUES (2406,7,'S600');
INSERT INTO model(id,brand_id,name) VALUES (2407,7,'S500');
INSERT INTO model(id,brand_id,name) VALUES (2408,7,'S800');
INSERT INTO model(id,brand_id,name) VALUES (2409,7,'STEPWGN');
INSERT INTO model(id,brand_id,name) VALUES (2410,7,'STREAM');
INSERT INTO model(id,brand_id,name) VALUES (2411,7,'THATS');
INSERT INTO model(id,brand_id,name) VALUES (2412,7,'VAMOZ');
INSERT INTO model(id,brand_id,name) VALUES (2413,7,'Z');
INSERT INTO model(id,brand_id,name) VALUES (2414,7,'ZEST');
INSERT INTO model(id,brand_id,name) VALUES (2441,59,'AERIO');
INSERT INTO model(id,brand_id,name) VALUES (2442,59,'ALTO');
INSERT INTO model(id,brand_id,name) VALUES (2443,59,'APV');
INSERT INTO model(id,brand_id,name) VALUES (2444,59,'KEI');
INSERT INTO model(id,brand_id,name) VALUES (2445,59,'LAPIN');
INSERT INTO model(id,brand_id,name) VALUES (2446,59,'MR WAGON');
INSERT INTO model(id,brand_id,name) VALUES (2447,59,'XL-7');
INSERT INTO model(id,brand_id,name) VALUES (2448,59,'VERONA');
INSERT INTO model(id,brand_id,name) VALUES (2477,158,'JEEP CJ');
INSERT INTO model(id,brand_id,name) VALUES (2479,22,'306 CABRIOLET');
INSERT INTO model(id,brand_id,name) VALUES (2484,57,'BELCAR');
INSERT INTO model(id,brand_id,name) VALUES (2485,90,'M715');
INSERT INTO model(id,brand_id,name) VALUES (2492,22,'407 SW');
INSERT INTO model(id,brand_id,name) VALUES (2493,22,'307 CC');
INSERT INTO model(id,brand_id,name) VALUES (2499,1,'STYLELINE');
INSERT INTO model(id,brand_id,name) VALUES (2500,13,'ANGLIA');
INSERT INTO model(id,brand_id,name) VALUES (2508,26,'GT2');
INSERT INTO model(id,brand_id,name) VALUES (2509,1,'YUKON');
INSERT INTO model(id,brand_id,name) VALUES (2510,54,'SPORTSMAN');
INSERT INTO model(id,brand_id,name) VALUES (2514,24,'21 NEVADA');
INSERT INTO model(id,brand_id,name) VALUES (2515,11,'VEYRON');
INSERT INTO model(id,brand_id,name) VALUES (2516,10,'ENZO');
INSERT INTO model(id,brand_id,name) VALUES (2517,22,'306 SW');
INSERT INTO model(id,brand_id,name) VALUES (2528,28,'TI 80');
INSERT INTO model(id,brand_id,name) VALUES (2532,70,'SPYDER 550');
INSERT INTO model(id,brand_id,name) VALUES (2533,10,'380 GTB');
INSERT INTO model(id,brand_id,name) VALUES (2534,149,'T-5');
INSERT INTO model(id,brand_id,name) VALUES (2536,18,'KINGSWAY');
INSERT INTO model(id,brand_id,name) VALUES (2537,1,'SSR');
INSERT INTO model(id,brand_id,name) VALUES (2540,1,'IMPALA');
INSERT INTO model(id,brand_id,name) VALUES (2541,22,'208');
INSERT INTO model(id,brand_id,name) VALUES (2542,1,'GRAND BLAZER');
INSERT INTO model(id,brand_id,name) VALUES (2555,53,'100 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (2558,53,'200 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (2559,53,'300 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (2561,53,'66');
INSERT INTO model(id,brand_id,name) VALUES (2562,53,'700 SERIES');
INSERT INTO model(id,brand_id,name) VALUES (2563,53,'AMAZON');
INSERT INTO model(id,brand_id,name) VALUES (2564,53,'C303');
INSERT INTO model(id,brand_id,name) VALUES (2566,53,'DUETT');
INSERT INTO model(id,brand_id,name) VALUES (2567,53,'L3314');
INSERT INTO model(id,brand_id,name) VALUES (2568,53,'OV 4');
INSERT INTO model(id,brand_id,name) VALUES (2569,53,'P1800');
INSERT INTO model(id,brand_id,name) VALUES (2570,53,'SUGGA');
INSERT INTO model(id,brand_id,name) VALUES (2571,13,'TT');
INSERT INTO model(id,brand_id,name) VALUES (2572,5,'ONCE');
INSERT INTO model(id,brand_id,name) VALUES (2573,13,'DE LUXE');
INSERT INTO model(id,brand_id,name) VALUES (2574,13,'CUSTOM');
INSERT INTO model(id,brand_id,name) VALUES (2575,13,'T-BUCKET');
INSERT INTO model(id,brand_id,name) VALUES (2576,17,'G15');
INSERT INTO model(id,brand_id,name) VALUES (2588,111,'PAJERO FULL 3D');
INSERT INTO model(id,brand_id,name) VALUES (2589,111,'PAJERO SPORT');
INSERT INTO model(id,brand_id,name) VALUES (2590,36,'120 CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2591,36,'320 TOURING');
INSERT INTO model(id,brand_id,name) VALUES (2592,36,'330 CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2593,36,'SERIE 5 TOURING');
INSERT INTO model(id,brand_id,name) VALUES (2594,36,'SERIE 6 CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2595,36,'SERIE M CONVERSIVEL');
INSERT INTO model(id,brand_id,name) VALUES (2596,36,'M5 TOURING');
INSERT INTO model(id,brand_id,name) VALUES (2597,36,'SERIE Z ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (2599,13,'KA SPORT');
INSERT INTO model(id,brand_id,name) VALUES (2600,2,'CC');
INSERT INTO model(id,brand_id,name) VALUES (2605,16,'CERATO KOUP');
INSERT INTO model(id,brand_id,name) VALUES (2607,1,'ASTRO');
INSERT INTO model(id,brand_id,name) VALUES (2608,23,'COROLLA XRS');
INSERT INTO model(id,brand_id,name) VALUES (2609,23,'ETIOS SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2611,13,'FREESTYLE');
INSERT INTO model(id,brand_id,name) VALUES (2612,110,'COUGAR');
INSERT INTO model(id,brand_id,name) VALUES (2615,102,'XUV 500');
INSERT INTO model(id,brand_id,name) VALUES (2618,102,'XYLO');
INSERT INTO model(id,brand_id,name) VALUES (2619,102,'BOLERO');
INSERT INTO model(id,brand_id,name) VALUES (2620,102,'THAR');
INSERT INTO model(id,brand_id,name) VALUES (2621,102,'AXE');
INSERT INTO model(id,brand_id,name) VALUES (2622,102,'LEGEND');
INSERT INTO model(id,brand_id,name) VALUES (2623,87,'CJ3');
INSERT INTO model(id,brand_id,name) VALUES (2624,102,'ARMADA');
INSERT INTO model(id,brand_id,name) VALUES (2625,102,'CHASSI');
INSERT INTO model(id,brand_id,name) VALUES (2626,102,'SCORPIO PICK-UP');
INSERT INTO model(id,brand_id,name) VALUES (2627,6,'STAR TRUCK');
INSERT INTO model(id,brand_id,name) VALUES (2628,6,'STAR');
INSERT INTO model(id,brand_id,name) VALUES (2629,6,'STAR VAN CARGO');
INSERT INTO model(id,brand_id,name) VALUES (2630,6,'STAR VAN PASSAGEIROS');
INSERT INTO model(id,brand_id,name) VALUES (2632,141,'ALVORADA');
INSERT INTO model(id,brand_id,name) VALUES (2633,141,'CHAMBORD');
INSERT INTO model(id,brand_id,name) VALUES (2637,141,'PROFISSIONAL');
INSERT INTO model(id,brand_id,name) VALUES (2639,141,'VEDETTE');
INSERT INTO model(id,brand_id,name) VALUES (2640,141,'ARONDE');
INSERT INTO model(id,brand_id,name) VALUES (2641,141,'1200S');
INSERT INTO model(id,brand_id,name) VALUES (2642,141,'1000');
INSERT INTO model(id,brand_id,name) VALUES (2645,14,'HB20X');
INSERT INTO model(id,brand_id,name) VALUES (2646,14,'HB20S');
INSERT INTO model(id,brand_id,name) VALUES (2648,1,'MONZA');
INSERT INTO model(id,brand_id,name) VALUES (2649,1,'CHEVETTE');
INSERT INTO model(id,brand_id,name) VALUES (2650,98,'X60');
INSERT INTO model(id,brand_id,name) VALUES (2651,1,'TRAX');
INSERT INTO model(id,brand_id,name) VALUES (2652,36,'118');
INSERT INTO model(id,brand_id,name) VALUES (2653,36,'120');
INSERT INTO model(id,brand_id,name) VALUES (2654,36,'130');
INSERT INTO model(id,brand_id,name) VALUES (2655,36,'BAVARIA');
INSERT INTO model(id,brand_id,name) VALUES (2656,36,'C-2800');
INSERT INTO model(id,brand_id,name) VALUES (2657,36,'318');
INSERT INTO model(id,brand_id,name) VALUES (2658,36,'320');
INSERT INTO model(id,brand_id,name) VALUES (2659,36,'318 CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2660,36,'325 CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (2661,36,'530');
INSERT INTO model(id,brand_id,name) VALUES (2662,36,'540');
INSERT INTO model(id,brand_id,name) VALUES (2663,36,'550');
INSERT INTO model(id,brand_id,name) VALUES (2664,36,'740');
INSERT INTO model(id,brand_id,name) VALUES (2665,36,'750');
INSERT INTO model(id,brand_id,name) VALUES (2666,36,'760');
INSERT INTO model(id,brand_id,name) VALUES (2675,341,'MATRIX 4X4');
INSERT INTO model(id,brand_id,name) VALUES (2694,132,'A7');
INSERT INTO model(id,brand_id,name) VALUES (2695,132,'A9');
INSERT INTO model(id,brand_id,name) VALUES (2696,132,'A9 CARGO');
INSERT INTO model(id,brand_id,name) VALUES (2697,132,'T20');
INSERT INTO model(id,brand_id,name) VALUES (2698,132,'T20 BAU');
INSERT INTO model(id,brand_id,name) VALUES (2699,132,'T22');
INSERT INTO model(id,brand_id,name) VALUES (2704,64,'SUPER 90 COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2705,17,'X20');
INSERT INTO model(id,brand_id,name) VALUES (2706,17,'ITAIPU');
INSERT INTO model(id,brand_id,name) VALUES (2707,17,'G800');
INSERT INTO model(id,brand_id,name) VALUES (2708,17,'XEF');
INSERT INTO model(id,brand_id,name) VALUES (2709,17,'MOTOMACHINE');
INSERT INTO model(id,brand_id,name) VALUES (2710,17,'BUGATO');
INSERT INTO model(id,brand_id,name) VALUES (2711,17,'QT');
INSERT INTO model(id,brand_id,name) VALUES (2716,57,'CAICARA');
INSERT INTO model(id,brand_id,name) VALUES (2717,57,'CARCARA');
INSERT INTO model(id,brand_id,name) VALUES (2718,57,'FISSORE');
INSERT INTO model(id,brand_id,name) VALUES (2719,57,'MALZONI');
INSERT INTO model(id,brand_id,name) VALUES (2720,57,'VEMAGUET');
INSERT INTO model(id,brand_id,name) VALUES (2727,5,'C4 LOUNGE');
INSERT INTO model(id,brand_id,name) VALUES (2728,108,'CX-7');
INSERT INTO model(id,brand_id,name) VALUES (2729,147,'TR');
INSERT INTO model(id,brand_id,name) VALUES (2730,147,'LUCENA');
INSERT INTO model(id,brand_id,name) VALUES (2731,147,'SEVETSE');
INSERT INTO model(id,brand_id,name) VALUES (2732,147,'RAGGE');
INSERT INTO model(id,brand_id,name) VALUES (2733,53,'C70');
INSERT INTO model(id,brand_id,name) VALUES (2734,53,'C30');
INSERT INTO model(id,brand_id,name) VALUES (2735,53,'544');
INSERT INTO model(id,brand_id,name) VALUES (2736,53,'S40');
INSERT INTO model(id,brand_id,name) VALUES (2737,53,'S60');
INSERT INTO model(id,brand_id,name) VALUES (2738,53,'S70');
INSERT INTO model(id,brand_id,name) VALUES (2739,53,'S80');
INSERT INTO model(id,brand_id,name) VALUES (2740,53,'V40');
INSERT INTO model(id,brand_id,name) VALUES (2741,53,'V50');
INSERT INTO model(id,brand_id,name) VALUES (2742,53,'V60');
INSERT INTO model(id,brand_id,name) VALUES (2743,53,'V70');
INSERT INTO model(id,brand_id,name) VALUES (2744,53,'S90');
INSERT INTO model(id,brand_id,name) VALUES (2745,53,'XC60');
INSERT INTO model(id,brand_id,name) VALUES (2746,53,'XC70');
INSERT INTO model(id,brand_id,name) VALUES (2747,53,'XC90');
INSERT INTO model(id,brand_id,name) VALUES (2748,53,'P1900');
INSERT INTO model(id,brand_id,name) VALUES (2749,53,'PV36');
INSERT INTO model(id,brand_id,name) VALUES (2750,53,'PV444');
INSERT INTO model(id,brand_id,name) VALUES (2751,53,'PV544');
INSERT INTO model(id,brand_id,name) VALUES (2752,53,'PV51');
INSERT INTO model(id,brand_id,name) VALUES (2753,53,'PV654');
INSERT INTO model(id,brand_id,name) VALUES (2754,53,'C50');
INSERT INTO model(id,brand_id,name) VALUES (2755,4,'190');
INSERT INTO model(id,brand_id,name) VALUES (2756,4,'CLASSE CLA');
INSERT INTO model(id,brand_id,name) VALUES (2757,4,'CLASSE V');
INSERT INTO model(id,brand_id,name) VALUES (2758,4,'VANEO');
INSERT INTO model(id,brand_id,name) VALUES (2759,4,'CITAN');
INSERT INTO model(id,brand_id,name) VALUES (2760,4,'VARIO');
INSERT INTO model(id,brand_id,name) VALUES (2761,4,'CLASSE S CLASSICO');
INSERT INTO model(id,brand_id,name) VALUES (2809,15,'J3S');
INSERT INTO model(id,brand_id,name) VALUES (2810,345,'PICK-UP');
INSERT INTO model(id,brand_id,name) VALUES (2811,345,'VAN');
INSERT INTO model(id,brand_id,name) VALUES (2823,5,'C3 SOLARIS');
INSERT INTO model(id,brand_id,name) VALUES (2824,5,'C3 XTR');
INSERT INTO model(id,brand_id,name) VALUES (2825,5,'C4 SOLARIS');
INSERT INTO model(id,brand_id,name) VALUES (2826,5,'C5 BREAK/TOURER');
INSERT INTO model(id,brand_id,name) VALUES (2827,5,'XSARA BREAK');
INSERT INTO model(id,brand_id,name) VALUES (2828,5,'XSARA VTS');
INSERT INTO model(id,brand_id,name) VALUES (2829,5,'XANTIA BREAK');
INSERT INTO model(id,brand_id,name) VALUES (2830,5,'XM BREAK');
INSERT INTO model(id,brand_id,name) VALUES (2831,5,'C15');
INSERT INTO model(id,brand_id,name) VALUES (2832,5,'NEMO');
INSERT INTO model(id,brand_id,name) VALUES (2833,5,'VISA');
INSERT INTO model(id,brand_id,name) VALUES (2834,5,'C1');
INSERT INTO model(id,brand_id,name) VALUES (2835,5,'C2');
INSERT INTO model(id,brand_id,name) VALUES (2836,5,'C3 PLURIEL');
INSERT INTO model(id,brand_id,name) VALUES (2837,5,'DS4');
INSERT INTO model(id,brand_id,name) VALUES (2838,5,'DS5');
INSERT INTO model(id,brand_id,name) VALUES (2839,5,'JUMPY');
INSERT INTO model(id,brand_id,name) VALUES (2840,5,'C-CROSSER');
INSERT INTO model(id,brand_id,name) VALUES (2841,5,'C35');
INSERT INTO model(id,brand_id,name) VALUES (2842,5,'C25');
INSERT INTO model(id,brand_id,name) VALUES (2843,5,'CX');
INSERT INTO model(id,brand_id,name) VALUES (2844,5,'CX BREAK');
INSERT INTO model(id,brand_id,name) VALUES (2845,5,'AXEL');
INSERT INTO model(id,brand_id,name) VALUES (2846,5,'DYANE');
INSERT INTO model(id,brand_id,name) VALUES (2847,5,'GS/GSA');
INSERT INTO model(id,brand_id,name) VALUES (2848,5,'GS/GSA BREAK');
INSERT INTO model(id,brand_id,name) VALUES (2849,5,'MEHARI');
INSERT INTO model(id,brand_id,name) VALUES (2850,5,'SAXO');
INSERT INTO model(id,brand_id,name) VALUES (2851,5,'SM');
INSERT INTO model(id,brand_id,name) VALUES (2852,5,'ELYSEE');
INSERT INTO model(id,brand_id,name) VALUES (2853,24,'MASTER MINIBUS');
INSERT INTO model(id,brand_id,name) VALUES (2854,47,'CELER');
INSERT INTO model(id,brand_id,name) VALUES (2855,47,'CELER SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2856,47,'CIELO SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2857,32,'A1 SPORTBACK');
INSERT INTO model(id,brand_id,name) VALUES (2858,32,'A1 QUATTRO');
INSERT INTO model(id,brand_id,name) VALUES (2859,32,'A3 SPORTBACK');
INSERT INTO model(id,brand_id,name) VALUES (2860,32,'RS4 AVANT');
INSERT INTO model(id,brand_id,name) VALUES (2861,32,'A8L W12');
INSERT INTO model(id,brand_id,name) VALUES (2862,32,'R8 V10');
INSERT INTO model(id,brand_id,name) VALUES (2863,13,'RANGER CD');
INSERT INTO model(id,brand_id,name) VALUES (2864,15,'T140');
INSERT INTO model(id,brand_id,name) VALUES (2865,36,'X1');
INSERT INTO model(id,brand_id,name) VALUES (2866,36,'X3');
INSERT INTO model(id,brand_id,name) VALUES (2867,36,'X5');
INSERT INTO model(id,brand_id,name) VALUES (2868,36,'X6');
INSERT INTO model(id,brand_id,name) VALUES (2869,36,'840');
INSERT INTO model(id,brand_id,name) VALUES (2870,36,'850');
INSERT INTO model(id,brand_id,name) VALUES (2871,36,'645');
INSERT INTO model(id,brand_id,name) VALUES (2872,36,'650');
INSERT INTO model(id,brand_id,name) VALUES (2874,7,'FIT TWIST');
INSERT INTO model(id,brand_id,name) VALUES (2876,346,'MP4');
INSERT INTO model(id,brand_id,name) VALUES (2877,346,'F1');
INSERT INTO model(id,brand_id,name) VALUES (2878,13,'MONDEO SW');
INSERT INTO model(id,brand_id,name) VALUES (2879,13,'ESCORT SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (2880,13,'ESCORT CONVERSIVEL');
INSERT INTO model(id,brand_id,name) VALUES (2881,108,'MX-6');
INSERT INTO model(id,brand_id,name) VALUES (2884,1,'CORISCO');
INSERT INTO model(id,brand_id,name) VALUES (2885,1,'CHEVELLE');
INSERT INTO model(id,brand_id,name) VALUES (2886,13,'EXCURSION');
INSERT INTO model(id,brand_id,name) VALUES (2887,2,'TOURAN');
INSERT INTO model(id,brand_id,name) VALUES (2890,13,'F-10000');
INSERT INTO model(id,brand_id,name) VALUES (2891,22,'HOGGAR ESCAPADE');
INSERT INTO model(id,brand_id,name) VALUES (2901,13,'PHAETON');
INSERT INTO model(id,brand_id,name) VALUES (2913,2,'TRANSPORTER');
INSERT INTO model(id,brand_id,name) VALUES (2914,16,'GRAND BESTA');
INSERT INTO model(id,brand_id,name) VALUES (2915,43,'200SX');
INSERT INTO model(id,brand_id,name) VALUES (2916,43,'240SX');
INSERT INTO model(id,brand_id,name) VALUES (2921,19,'300M');
INSERT INTO model(id,brand_id,name) VALUES (2922,19,'300C TOURING');
INSERT INTO model(id,brand_id,name) VALUES (2928,13,'TORINO');
INSERT INTO model(id,brand_id,name) VALUES (2931,1,'VENTURE');
INSERT INTO model(id,brand_id,name) VALUES (2932,1,'FLEETLINE');
INSERT INTO model(id,brand_id,name) VALUES (2933,1,'FLEETMASTER');
INSERT INTO model(id,brand_id,name) VALUES (2934,1,'DELUXE');
INSERT INTO model(id,brand_id,name) VALUES (2936,13,'ESCORT XR3');
INSERT INTO model(id,brand_id,name) VALUES (2937,1,'MASTER');
INSERT INTO model(id,brand_id,name) VALUES (2938,120,'TORONADO');
INSERT INTO model(id,brand_id,name) VALUES (2939,120,'SIX');
INSERT INTO model(id,brand_id,name) VALUES (2940,120,'EIGHT');
INSERT INTO model(id,brand_id,name) VALUES (2941,120,'DELUXE');
INSERT INTO model(id,brand_id,name) VALUES (2942,120,'SERIES 60');
INSERT INTO model(id,brand_id,name) VALUES (2943,120,'SERIES 70');
INSERT INTO model(id,brand_id,name) VALUES (2944,120,'SERIES 80');
INSERT INTO model(id,brand_id,name) VALUES (2945,120,'SERIES 90');
INSERT INTO model(id,brand_id,name) VALUES (2946,120,'STARFIRE');
INSERT INTO model(id,brand_id,name) VALUES (2947,120,'442');
INSERT INTO model(id,brand_id,name) VALUES (2948,120,'CUTLASS');
INSERT INTO model(id,brand_id,name) VALUES (2949,120,'CUTLASS SUPREME');
INSERT INTO model(id,brand_id,name) VALUES (2950,120,'CUTLASS SALON');
INSERT INTO model(id,brand_id,name) VALUES (2951,120,'CUTLASS CALAIS');
INSERT INTO model(id,brand_id,name) VALUES (2952,120,'CUTLASS CIERA');
INSERT INTO model(id,brand_id,name) VALUES (2953,120,'CUSTOM CRUISER');
INSERT INTO model(id,brand_id,name) VALUES (2954,120,'VISTA CRUISER');
INSERT INTO model(id,brand_id,name) VALUES (2955,120,'F-85');
INSERT INTO model(id,brand_id,name) VALUES (2957,120,'FIRENZA');
INSERT INTO model(id,brand_id,name) VALUES (2958,120,'ACHIEVA');
INSERT INTO model(id,brand_id,name) VALUES (2959,120,'ALERO');
INSERT INTO model(id,brand_id,name) VALUES (2960,120,'AURORA');
INSERT INTO model(id,brand_id,name) VALUES (2961,120,'BRAVADA');
INSERT INTO model(id,brand_id,name) VALUES (2962,120,'INTRIGUE');
INSERT INTO model(id,brand_id,name) VALUES (2963,120,'SILHOUETTE');
INSERT INTO model(id,brand_id,name) VALUES (2972,123,'SUPERBIRD');
INSERT INTO model(id,brand_id,name) VALUES (2973,123,'FURY');
INSERT INTO model(id,brand_id,name) VALUES (2974,123,'SPECIAL');
INSERT INTO model(id,brand_id,name) VALUES (2975,123,'PROWLER');
INSERT INTO model(id,brand_id,name) VALUES (2976,123,'TRAIL DUSTER');
INSERT INTO model(id,brand_id,name) VALUES (2977,123,'VOYAGER');
INSERT INTO model(id,brand_id,name) VALUES (2978,123,'SCAMP');
INSERT INTO model(id,brand_id,name) VALUES (2979,123,'ARROW');
INSERT INTO model(id,brand_id,name) VALUES (2980,123,'PT50');
INSERT INTO model(id,brand_id,name) VALUES (2981,123,'PT57');
INSERT INTO model(id,brand_id,name) VALUES (2982,123,'PT81');
INSERT INTO model(id,brand_id,name) VALUES (2983,123,'PT105');
INSERT INTO model(id,brand_id,name) VALUES (2984,123,'PT125');
INSERT INTO model(id,brand_id,name) VALUES (2985,123,'EXPRESS');
INSERT INTO model(id,brand_id,name) VALUES (2986,123,'VOYAGER EXPRESSO');
INSERT INTO model(id,brand_id,name) VALUES (2987,123,'NEON');
INSERT INTO model(id,brand_id,name) VALUES (2988,123,'LASER');
INSERT INTO model(id,brand_id,name) VALUES (2989,123,'CARAVELLE');
INSERT INTO model(id,brand_id,name) VALUES (2990,123,'STATION WAGON');
INSERT INTO model(id,brand_id,name) VALUES (2991,123,'MODEL Q');
INSERT INTO model(id,brand_id,name) VALUES (2992,123,'MODEL P6');
INSERT INTO model(id,brand_id,name) VALUES (2993,31,'DB9 COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2994,31,'DB9 VOLANTE');
INSERT INTO model(id,brand_id,name) VALUES (2995,31,'VIRAGE COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2996,31,'RAPidE S');
INSERT INTO model(id,brand_id,name) VALUES (2997,31,'V12 VANTAGE');
INSERT INTO model(id,brand_id,name) VALUES (2998,31,'V8 VANTAGE COUPE');
INSERT INTO model(id,brand_id,name) VALUES (2999,31,'V8 VANTAGE ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (3000,31,'V8 VANTAGE S COUPE');
INSERT INTO model(id,brand_id,name) VALUES (3001,31,'V8 VANTAGE S ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (3002,31,'VANQUISH COUPE');
INSERT INTO model(id,brand_id,name) VALUES (3003,31,'VANQUISH VOLANTE');
INSERT INTO model(id,brand_id,name) VALUES (3004,31,'V12 ZAGATO');
INSERT INTO model(id,brand_id,name) VALUES (3005,31,'DB5');
INSERT INTO model(id,brand_id,name) VALUES (3007,31,'DBS');
INSERT INTO model(id,brand_id,name) VALUES (3008,31,'DBS VOLANTE');
INSERT INTO model(id,brand_id,name) VALUES (3009,31,'CYGNET');
INSERT INTO model(id,brand_id,name) VALUES (3010,31,'ONE-77');
INSERT INTO model(id,brand_id,name) VALUES (3011,31,'DBR9');
INSERT INTO model(id,brand_id,name) VALUES (3013,36,'M3');
INSERT INTO model(id,brand_id,name) VALUES (3014,36,'M5');
INSERT INTO model(id,brand_id,name) VALUES (3015,36,'M6');
INSERT INTO model(id,brand_id,name) VALUES (3016,36,'X6 M');
INSERT INTO model(id,brand_id,name) VALUES (3017,113,'CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (3018,113,'COUPE');
INSERT INTO model(id,brand_id,name) VALUES (3019,113,'ROADSTER');
INSERT INTO model(id,brand_id,name) VALUES (3020,113,'COUNTRYMAN');
INSERT INTO model(id,brand_id,name) VALUES (3021,113,'PACEMAN');
INSERT INTO model(id,brand_id,name) VALUES (3022,113,'JOHN COOPER WORKS');
INSERT INTO model(id,brand_id,name) VALUES (3023,122,'ZONDA');
INSERT INTO model(id,brand_id,name) VALUES (3024,8,'NEW XV');
INSERT INTO model(id,brand_id,name) VALUES (3025,8,'IMPREZA WRX HATCH');
INSERT INTO model(id,brand_id,name) VALUES (3026,8,'IMPREZA WRX STI HATCH');
INSERT INTO model(id,brand_id,name) VALUES (3027,8,'IMPREZA WRX STI SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (3028,8,'IMPREZA WRX SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (3030,23,'ETIOS CROSS');
INSERT INTO model(id,brand_id,name) VALUES (3031,12,'HURACAN');
INSERT INTO model(id,brand_id,name) VALUES (3032,2,'UP');
INSERT INTO model(id,brand_id,name) VALUES (4964,142,'FORTWO CABRIO');
INSERT INTO model(id,brand_id,name) VALUES (4969,26,'GT');
INSERT INTO model(id,brand_id,name) VALUES (4970,26,'GTL');
INSERT INTO model(id,brand_id,name) VALUES (4971,26,'GTM');
INSERT INTO model(id,brand_id,name) VALUES (4972,26,'C2');
INSERT INTO model(id,brand_id,name) VALUES (4973,26,'CRX');
INSERT INTO model(id,brand_id,name) VALUES (4974,26,'AC 2000');
INSERT INTO model(id,brand_id,name) VALUES (4975,99,'AVIATOR');
INSERT INTO model(id,brand_id,name) VALUES (4976,99,'BLACKWOOD');
INSERT INTO model(id,brand_id,name) VALUES (4977,99,'CAPRI');
INSERT INTO model(id,brand_id,name) VALUES (4978,99,'CONTINENTAL');
INSERT INTO model(id,brand_id,name) VALUES (4979,99,'LS');
INSERT INTO model(id,brand_id,name) VALUES (4980,99,'MARK');
INSERT INTO model(id,brand_id,name) VALUES (4981,99,'MARK LT');
INSERT INTO model(id,brand_id,name) VALUES (4982,99,'MKR');
INSERT INTO model(id,brand_id,name) VALUES (4983,99,'MKS');
INSERT INTO model(id,brand_id,name) VALUES (4984,99,'MKX');
INSERT INTO model(id,brand_id,name) VALUES (4985,99,'MKZ');
INSERT INTO model(id,brand_id,name) VALUES (4986,99,'NAVIGATOR');
INSERT INTO model(id,brand_id,name) VALUES (4987,99,'PREMIERE');
INSERT INTO model(id,brand_id,name) VALUES (4988,99,'TOWN CAR');
INSERT INTO model(id,brand_id,name) VALUES (4989,99,'VERSAILLES');
INSERT INTO model(id,brand_id,name) VALUES (4990,99,'ZEPHYR');
INSERT INTO model(id,brand_id,name) VALUES (4991,1,'CLASSIC');
INSERT INTO model(id,brand_id,name) VALUES (4992,21,'ACTYON');
INSERT INTO model(id,brand_id,name) VALUES (5003,1,'MARAJO');
INSERT INTO model(id,brand_id,name) VALUES (5004,1,'SUPREMA');
INSERT INTO model(id,brand_id,name) VALUES (5005,2,'NEW BEETLE');
INSERT INTO model(id,brand_id,name) VALUES (5006,2,'QUANTUM');
INSERT INTO model(id,brand_id,name) VALUES (5007,2,'CROSSFOX');
INSERT INTO model(id,brand_id,name) VALUES (5008,3,'MILLE');
INSERT INTO model(id,brand_id,name) VALUES (5009,534,'GC2');
INSERT INTO model(id,brand_id,name) VALUES (5010,534,'EC7');
INSERT INTO model(id,brand_id,name) VALUES (5011,98,'530');
INSERT INTO model(id,brand_id,name) VALUES (5012,3,'MOBI');
INSERT INTO model(id,brand_id,name) VALUES (5013,3,'TORO');
INSERT INTO model(id,brand_id,name) VALUES (5014,87,'RENEGADE');
INSERT INTO model(id,brand_id,name) VALUES (5015,24,'DUSTER OROCH');
INSERT INTO model(id,brand_id,name) VALUES (5016,24,'SANDERO RS');
INSERT INTO model(id,brand_id,name) VALUES (5017,14,'HB20R');
INSERT INTO model(id,brand_id,name) VALUES (5018,14,'GRAND SANTA FE');
INSERT INTO model(id,brand_id,name) VALUES (5019,2,'GOLF VARIANT');
INSERT INTO model(id,brand_id,name) VALUES (5020,2,'SPACE CROSS');
INSERT INTO model(id,brand_id,name) VALUES (5021,22,'2008');
INSERT INTO model(id,brand_id,name) VALUES (5022,16,'QUORIS');
INSERT INTO model(id,brand_id,name) VALUES (5023,16,'GRAND CARNIVAL');
INSERT INTO model(id,brand_id,name) VALUES (5024,15,'T8');
INSERT INTO model(id,brand_id,name) VALUES (5025,15,'T6');
INSERT INTO model(id,brand_id,name) VALUES (5026,15,'T5');
INSERT INTO model(id,brand_id,name) VALUES (5027,13,'KA SEDAN');
INSERT INTO model(id,brand_id,name) VALUES (5028,13,'FOCUS FASTBACK');
